//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 12:36:44 PM CET 
//


package io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for actualUseInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="actualUseInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="applicationsInvolved" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="applicationInvolved" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}applicationType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}applicationOther" minOccurs="0"/>
 *         &lt;element name="usageReports" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="usageReport" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}relatedDocumentInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="derivedResources" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="derivedResource" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}relatedResourceType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="usageProjects" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="usageProject" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}projectInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="actualUseDetails" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "actualUseInfoType", propOrder = {
    "applicationsInvolved",
    "applicationOther",
    "usageReports",
    "derivedResources",
    "usageProjects",
    "actualUseDetails"
})
public class ActualUseInfoType {

    protected ActualUseInfoType.ApplicationsInvolved applicationsInvolved;
    protected String applicationOther;
    protected ActualUseInfoType.UsageReports usageReports;
    protected ActualUseInfoType.DerivedResources derivedResources;
    protected ActualUseInfoType.UsageProjects usageProjects;
    protected String actualUseDetails;

    /**
     * Gets the value of the applicationsInvolved property.
     * 
     * @return
     *     possible object is
     *     {@link ActualUseInfoType.ApplicationsInvolved }
     *     
     */
    public ActualUseInfoType.ApplicationsInvolved getApplicationsInvolved() {
        return applicationsInvolved;
    }

    /**
     * Sets the value of the applicationsInvolved property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActualUseInfoType.ApplicationsInvolved }
     *     
     */
    public void setApplicationsInvolved(ActualUseInfoType.ApplicationsInvolved value) {
        this.applicationsInvolved = value;
    }

    /**
     * Gets the value of the applicationOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationOther() {
        return applicationOther;
    }

    /**
     * Sets the value of the applicationOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationOther(String value) {
        this.applicationOther = value;
    }

    /**
     * Gets the value of the usageReports property.
     * 
     * @return
     *     possible object is
     *     {@link ActualUseInfoType.UsageReports }
     *     
     */
    public ActualUseInfoType.UsageReports getUsageReports() {
        return usageReports;
    }

    /**
     * Sets the value of the usageReports property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActualUseInfoType.UsageReports }
     *     
     */
    public void setUsageReports(ActualUseInfoType.UsageReports value) {
        this.usageReports = value;
    }

    /**
     * Gets the value of the derivedResources property.
     * 
     * @return
     *     possible object is
     *     {@link ActualUseInfoType.DerivedResources }
     *     
     */
    public ActualUseInfoType.DerivedResources getDerivedResources() {
        return derivedResources;
    }

    /**
     * Sets the value of the derivedResources property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActualUseInfoType.DerivedResources }
     *     
     */
    public void setDerivedResources(ActualUseInfoType.DerivedResources value) {
        this.derivedResources = value;
    }

    /**
     * Gets the value of the usageProjects property.
     * 
     * @return
     *     possible object is
     *     {@link ActualUseInfoType.UsageProjects }
     *     
     */
    public ActualUseInfoType.UsageProjects getUsageProjects() {
        return usageProjects;
    }

    /**
     * Sets the value of the usageProjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActualUseInfoType.UsageProjects }
     *     
     */
    public void setUsageProjects(ActualUseInfoType.UsageProjects value) {
        this.usageProjects = value;
    }

    /**
     * Gets the value of the actualUseDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActualUseDetails() {
        return actualUseDetails;
    }

    /**
     * Sets the value of the actualUseDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActualUseDetails(String value) {
        this.actualUseDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="applicationInvolved" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}applicationType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "applicationInvolved"
    })
    public static class ApplicationsInvolved {

        @XmlSchemaType(name = "anyURI")
        protected List<String> applicationInvolved;

        /**
         * Gets the value of the applicationInvolved property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the applicationInvolved property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getApplicationInvolved().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getApplicationInvolved() {
            if (applicationInvolved == null) {
                applicationInvolved = new ArrayList<String>();
            }
            return this.applicationInvolved;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="derivedResource" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}relatedResourceType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "derivedResource"
    })
    public static class DerivedResources {

        protected List<RelatedResourceType> derivedResource;

        /**
         * Gets the value of the derivedResource property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the derivedResource property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDerivedResource().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RelatedResourceType }
         * 
         * 
         */
        public List<RelatedResourceType> getDerivedResource() {
            if (derivedResource == null) {
                derivedResource = new ArrayList<RelatedResourceType>();
            }
            return this.derivedResource;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="usageProject" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}projectInfoType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "usageProject"
    })
    public static class UsageProjects {

        protected List<ProjectInfoType> usageProject;

        /**
         * Gets the value of the usageProject property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the usageProject property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUsageProject().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProjectInfoType }
         * 
         * 
         */
        public List<ProjectInfoType> getUsageProject() {
            if (usageProject == null) {
                usageProject = new ArrayList<ProjectInfoType>();
            }
            return this.usageProject;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="usageReport" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}relatedDocumentInfoType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "usageReport"
    })
    public static class UsageReports {

        protected List<RelatedDocumentInfoType> usageReport;

        /**
         * Gets the value of the usageReport property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the usageReport property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUsageReport().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RelatedDocumentInfoType }
         * 
         * 
         */
        public List<RelatedDocumentInfoType> getUsageReport() {
            if (usageReport == null) {
                usageReport = new ArrayList<RelatedDocumentInfoType>();
            }
            return this.usageReport;
        }

    }

}
