//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 12:36:44 PM CET 
//


package io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for componentDistributionInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="componentDistributionInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="componentDistributionForm">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="webService"/>
 *               &lt;enumeration value="sourceCode"/>
 *               &lt;enumeration value="executableCode"/>
 *               &lt;enumeration value="sourceAndExecutableCode"/>
 *               &lt;enumeration value="dockerImage"/>
 *               &lt;enumeration value="galaxyWorkflow"/>
 *               &lt;enumeration value="workflowFile"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}distributionLocation"/>
 *         &lt;element name="command" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="webServiceType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="REST"/>
 *               &lt;enumeration value="SOAP"/>
 *               &lt;enumeration value="other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="operatingSystems" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="operatingSystem" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="50"/>
 *                         &lt;enumeration value="os-independent"/>
 *                         &lt;enumeration value="windows"/>
 *                         &lt;enumeration value="linux"/>
 *                         &lt;enumeration value="unix"/>
 *                         &lt;enumeration value="mac-OS"/>
 *                         &lt;enumeration value="googleChromeOS"/>
 *                         &lt;enumeration value="iOS"/>
 *                         &lt;enumeration value="android"/>
 *                         &lt;enumeration value="other"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "componentDistributionInfoType", propOrder = {
    "componentDistributionForm",
    "distributionLocation",
    "command",
    "webServiceType",
    "operatingSystems"
})
public class ComponentDistributionInfoType {

    @XmlElement(required = true)
    protected String componentDistributionForm;
    @XmlElement(required = true)
    protected String distributionLocation;
    protected String command;
    protected String webServiceType;
    protected ComponentDistributionInfoType.OperatingSystems operatingSystems;

    /**
     * Gets the value of the componentDistributionForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentDistributionForm() {
        return componentDistributionForm;
    }

    /**
     * Sets the value of the componentDistributionForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentDistributionForm(String value) {
        this.componentDistributionForm = value;
    }

    /**
     * Gets the value of the distributionLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistributionLocation() {
        return distributionLocation;
    }

    /**
     * Sets the value of the distributionLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistributionLocation(String value) {
        this.distributionLocation = value;
    }

    /**
     * Gets the value of the command property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommand() {
        return command;
    }

    /**
     * Sets the value of the command property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommand(String value) {
        this.command = value;
    }

    /**
     * Gets the value of the webServiceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebServiceType() {
        return webServiceType;
    }

    /**
     * Sets the value of the webServiceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebServiceType(String value) {
        this.webServiceType = value;
    }

    /**
     * Gets the value of the operatingSystems property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentDistributionInfoType.OperatingSystems }
     *     
     */
    public ComponentDistributionInfoType.OperatingSystems getOperatingSystems() {
        return operatingSystems;
    }

    /**
     * Sets the value of the operatingSystems property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentDistributionInfoType.OperatingSystems }
     *     
     */
    public void setOperatingSystems(ComponentDistributionInfoType.OperatingSystems value) {
        this.operatingSystems = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="operatingSystem" maxOccurs="unbounded" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="50"/>
     *               &lt;enumeration value="os-independent"/>
     *               &lt;enumeration value="windows"/>
     *               &lt;enumeration value="linux"/>
     *               &lt;enumeration value="unix"/>
     *               &lt;enumeration value="mac-OS"/>
     *               &lt;enumeration value="googleChromeOS"/>
     *               &lt;enumeration value="iOS"/>
     *               &lt;enumeration value="android"/>
     *               &lt;enumeration value="other"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "operatingSystem"
    })
    public static class OperatingSystems {

        protected List<String> operatingSystem;

        /**
         * Gets the value of the operatingSystem property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the operatingSystem property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOperatingSystem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getOperatingSystem() {
            if (operatingSystem == null) {
                operatingSystem = new ArrayList<String>();
            }
            return this.operatingSystem;
        }

    }

}
