//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 12:36:44 PM CET 
//


package io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for contactInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="contactInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contactPoint" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contactType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="landingPage"/>
 *               &lt;enumeration value="contactEmail"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="contactPersons" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="contactPerson" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}personInfoType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="contactGroups" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="contactGroup" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}groupInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="mailingLists" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="mailingListInfo" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}mailingListInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "contactInfoType", propOrder = {
    "contactPoint",
    "contactType",
    "contactPersons",
    "contactGroups",
    "mailingLists"
})
public class ContactInfoType {

    @XmlElement(required = true)
    protected String contactPoint;
    @XmlElement(required = true)
    protected String contactType;
    protected ContactInfoType.ContactPersons contactPersons;
    protected ContactInfoType.ContactGroups contactGroups;
    protected ContactInfoType.MailingLists mailingLists;

    /**
     * Gets the value of the contactPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactPoint() {
        return contactPoint;
    }

    /**
     * Sets the value of the contactPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactPoint(String value) {
        this.contactPoint = value;
    }

    /**
     * Gets the value of the contactType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactType() {
        return contactType;
    }

    /**
     * Sets the value of the contactType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactType(String value) {
        this.contactType = value;
    }

    /**
     * Gets the value of the contactPersons property.
     * 
     * @return
     *     possible object is
     *     {@link ContactInfoType.ContactPersons }
     *     
     */
    public ContactInfoType.ContactPersons getContactPersons() {
        return contactPersons;
    }

    /**
     * Sets the value of the contactPersons property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactInfoType.ContactPersons }
     *     
     */
    public void setContactPersons(ContactInfoType.ContactPersons value) {
        this.contactPersons = value;
    }

    /**
     * Gets the value of the contactGroups property.
     * 
     * @return
     *     possible object is
     *     {@link ContactInfoType.ContactGroups }
     *     
     */
    public ContactInfoType.ContactGroups getContactGroups() {
        return contactGroups;
    }

    /**
     * Sets the value of the contactGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactInfoType.ContactGroups }
     *     
     */
    public void setContactGroups(ContactInfoType.ContactGroups value) {
        this.contactGroups = value;
    }

    /**
     * Gets the value of the mailingLists property.
     * 
     * @return
     *     possible object is
     *     {@link ContactInfoType.MailingLists }
     *     
     */
    public ContactInfoType.MailingLists getMailingLists() {
        return mailingLists;
    }

    /**
     * Sets the value of the mailingLists property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactInfoType.MailingLists }
     *     
     */
    public void setMailingLists(ContactInfoType.MailingLists value) {
        this.mailingLists = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="contactGroup" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}groupInfoType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contactGroup"
    })
    public static class ContactGroups {

        protected List<GroupInfoType> contactGroup;

        /**
         * Gets the value of the contactGroup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the contactGroup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContactGroup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GroupInfoType }
         * 
         * 
         */
        public List<GroupInfoType> getContactGroup() {
            if (contactGroup == null) {
                contactGroup = new ArrayList<GroupInfoType>();
            }
            return this.contactGroup;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="contactPerson" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}personInfoType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contactPerson"
    })
    public static class ContactPersons {

        @XmlElement(required = true)
        protected List<PersonInfoType> contactPerson;

        /**
         * Gets the value of the contactPerson property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the contactPerson property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContactPerson().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PersonInfoType }
         * 
         * 
         */
        public List<PersonInfoType> getContactPerson() {
            if (contactPerson == null) {
                contactPerson = new ArrayList<PersonInfoType>();
            }
            return this.contactPerson;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="mailingListInfo" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}mailingListInfoType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mailingListInfo"
    })
    public static class MailingLists {

        protected List<MailingListInfoType> mailingListInfo;

        /**
         * Gets the value of the mailingListInfo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the mailingListInfo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMailingListInfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MailingListInfoType }
         * 
         * 
         */
        public List<MailingListInfoType> getMailingListInfo() {
            if (mailingListInfo == null) {
                mailingListInfo = new ArrayList<MailingListInfoType>();
            }
            return this.mailingListInfo;
        }

    }

}
