//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 12:36:44 PM CET 
//


package io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for creationInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="creationInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="originalSources" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="hasOriginalSource" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}relatedResourceType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="creationMode" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}processMode" minOccurs="0"/>
 *         &lt;element name="creationModeDetails" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="creationSwComponents" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="isCreatedBy" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}relatedResourceType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "creationInfoType", propOrder = {
    "originalSources",
    "creationMode",
    "creationModeDetails",
    "creationSwComponents"
})
public class CreationInfoType {

    protected CreationInfoType.OriginalSources originalSources;
    @XmlSchemaType(name = "string")
    protected ProcessMode creationMode;
    protected String creationModeDetails;
    protected CreationInfoType.CreationSwComponents creationSwComponents;

    /**
     * Gets the value of the originalSources property.
     * 
     * @return
     *     possible object is
     *     {@link CreationInfoType.OriginalSources }
     *     
     */
    public CreationInfoType.OriginalSources getOriginalSources() {
        return originalSources;
    }

    /**
     * Sets the value of the originalSources property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreationInfoType.OriginalSources }
     *     
     */
    public void setOriginalSources(CreationInfoType.OriginalSources value) {
        this.originalSources = value;
    }

    /**
     * Gets the value of the creationMode property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessMode }
     *     
     */
    public ProcessMode getCreationMode() {
        return creationMode;
    }

    /**
     * Sets the value of the creationMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessMode }
     *     
     */
    public void setCreationMode(ProcessMode value) {
        this.creationMode = value;
    }

    /**
     * Gets the value of the creationModeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationModeDetails() {
        return creationModeDetails;
    }

    /**
     * Sets the value of the creationModeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationModeDetails(String value) {
        this.creationModeDetails = value;
    }

    /**
     * Gets the value of the creationSwComponents property.
     * 
     * @return
     *     possible object is
     *     {@link CreationInfoType.CreationSwComponents }
     *     
     */
    public CreationInfoType.CreationSwComponents getCreationSwComponents() {
        return creationSwComponents;
    }

    /**
     * Sets the value of the creationSwComponents property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreationInfoType.CreationSwComponents }
     *     
     */
    public void setCreationSwComponents(CreationInfoType.CreationSwComponents value) {
        this.creationSwComponents = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="isCreatedBy" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}relatedResourceType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "isCreatedBy"
    })
    public static class CreationSwComponents {

        protected List<RelatedResourceType> isCreatedBy;

        /**
         * Gets the value of the isCreatedBy property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the isCreatedBy property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIsCreatedBy().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RelatedResourceType }
         * 
         * 
         */
        public List<RelatedResourceType> getIsCreatedBy() {
            if (isCreatedBy == null) {
                isCreatedBy = new ArrayList<RelatedResourceType>();
            }
            return this.isCreatedBy;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="hasOriginalSource" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}relatedResourceType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hasOriginalSource"
    })
    public static class OriginalSources {

        protected List<RelatedResourceType> hasOriginalSource;

        /**
         * Gets the value of the hasOriginalSource property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the hasOriginalSource property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHasOriginalSource().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RelatedResourceType }
         * 
         * 
         */
        public List<RelatedResourceType> getHasOriginalSource() {
            if (hasOriginalSource == null) {
                hasOriginalSource = new ArrayList<RelatedResourceType>();
            }
            return this.hasOriginalSource;
        }

    }

}
