//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 12:36:44 PM CET 
//


package io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Base type for groups; group name and affiliations
 * 
 * <p>Java class for groupInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="groupInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="groupNames">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="groupName" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;restriction base="&lt;http://www.meta-share.org/OMTD-SHARE_XMLSchema>myString">
 *                         &lt;/restriction>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="affiliatedOrganization" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}organizationInfoType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "groupInfoType", propOrder = {
    "groupNames",
    "affiliatedOrganization"
})
public class GroupInfoType {

    @XmlElement(required = true)
    protected GroupInfoType.GroupNames groupNames;
    protected OrganizationInfoType affiliatedOrganization;

    /**
     * Gets the value of the groupNames property.
     * 
     * @return
     *     possible object is
     *     {@link GroupInfoType.GroupNames }
     *     
     */
    public GroupInfoType.GroupNames getGroupNames() {
        return groupNames;
    }

    /**
     * Sets the value of the groupNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupInfoType.GroupNames }
     *     
     */
    public void setGroupNames(GroupInfoType.GroupNames value) {
        this.groupNames = value;
    }

    /**
     * Gets the value of the affiliatedOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationInfoType }
     *     
     */
    public OrganizationInfoType getAffiliatedOrganization() {
        return affiliatedOrganization;
    }

    /**
     * Sets the value of the affiliatedOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationInfoType }
     *     
     */
    public void setAffiliatedOrganization(OrganizationInfoType value) {
        this.affiliatedOrganization = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="groupName" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;restriction base="&lt;http://www.meta-share.org/OMTD-SHARE_XMLSchema>myString">
     *               &lt;/restriction>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "groupName"
    })
    public static class GroupNames {

        @XmlElement(required = true)
        protected List<GroupInfoType.GroupNames.GroupName> groupName;

        /**
         * Gets the value of the groupName property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the groupName property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGroupName().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GroupInfoType.GroupNames.GroupName }
         * 
         * 
         */
        public List<GroupInfoType.GroupNames.GroupName> getGroupName() {
            if (groupName == null) {
                groupName = new ArrayList<GroupInfoType.GroupNames.GroupName>();
            }
            return this.groupName;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;restriction base="&lt;http://www.meta-share.org/OMTD-SHARE_XMLSchema>myString">
         *     &lt;/restriction>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class GroupName
            extends MyString
        {


        }

    }

}
