//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 12:36:44 PM CET 
//


package io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}baseMetadataRecord">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}lexicalConceptualResourceInfo"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lexicalConceptualResourceInfo"
})
@XmlRootElement(name = "lcrMetadataRecord")
public class LcrMetadataRecord
    extends BaseMetadataRecord
{

    @XmlElement(required = true)
    protected LexicalConceptualResourceInfoType lexicalConceptualResourceInfo;

    /**
     * Gets the value of the lexicalConceptualResourceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LexicalConceptualResourceInfoType }
     *     
     */
    public LexicalConceptualResourceInfoType getLexicalConceptualResourceInfo() {
        return lexicalConceptualResourceInfo;
    }

    /**
     * Sets the value of the lexicalConceptualResourceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LexicalConceptualResourceInfoType }
     *     
     */
    public void setLexicalConceptualResourceInfo(LexicalConceptualResourceInfoType value) {
        this.lexicalConceptualResourceInfo = value;
    }

}
