//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 12:36:44 PM CET 
//


package io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lexicalConceptualResourceEncodingInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lexicalConceptualResourceEncodingInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contentTypes" maxOccurs="unbounded">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;enumeration value="accentuation"/>
 *               &lt;enumeration value="lemma"/>
 *               &lt;enumeration value="lemma-MultiWordUnits"/>
 *               &lt;enumeration value="lemma-Variants"/>
 *               &lt;enumeration value="lemma-Abbreviations"/>
 *               &lt;enumeration value="lemma-Compounds"/>
 *               &lt;enumeration value="lemma-CliticForms"/>
 *               &lt;enumeration value="partOfSpeech"/>
 *               &lt;enumeration value="morpho-Features"/>
 *               &lt;enumeration value="morpho-Case"/>
 *               &lt;enumeration value="morpho-Gender"/>
 *               &lt;enumeration value="morpho-Number"/>
 *               &lt;enumeration value="morpho-Degree"/>
 *               &lt;enumeration value="morpho-IrregularForms"/>
 *               &lt;enumeration value="morpho-Mood"/>
 *               &lt;enumeration value="morpho-Tense"/>
 *               &lt;enumeration value="morpho-Person"/>
 *               &lt;enumeration value="morpho-Aspect"/>
 *               &lt;enumeration value="morpho-Voice"/>
 *               &lt;enumeration value="morpho-Auxiliary"/>
 *               &lt;enumeration value="morpho-Inflection"/>
 *               &lt;enumeration value="morpho-Reflexivity"/>
 *               &lt;enumeration value="syntax-SubcatFrame"/>
 *               &lt;enumeration value="semantics-Traits"/>
 *               &lt;enumeration value="semantics-SemanticClass"/>
 *               &lt;enumeration value="semantics-CrossReferences"/>
 *               &lt;enumeration value="semantics-Relations"/>
 *               &lt;enumeration value="semantics-Relations-Hyponyms"/>
 *               &lt;enumeration value="semantics-Relations-Hyperonyms"/>
 *               &lt;enumeration value="semantics-Relations-Synonyms"/>
 *               &lt;enumeration value="semantics-Relations-Antonyms"/>
 *               &lt;enumeration value="semantics-Relations-Troponyms"/>
 *               &lt;enumeration value="semantics-Relations-Meronyms"/>
 *               &lt;enumeration value="usage-Frequency"/>
 *               &lt;enumeration value="usage-Register"/>
 *               &lt;enumeration value="usage-Collocations"/>
 *               &lt;enumeration value="usage-Examples"/>
 *               &lt;enumeration value="usage-Notes"/>
 *               &lt;enumeration value="definition/gloss"/>
 *               &lt;enumeration value="translationEquivalent"/>
 *               &lt;enumeration value="semantics-Domain"/>
 *               &lt;enumeration value="semantics-EventType"/>
 *               &lt;enumeration value="semantics-SemanticRoles"/>
 *               &lt;enumeration value="statisticalProperties"/>
 *               &lt;enumeration value="morpho-Derivation"/>
 *               &lt;enumeration value="semantics-QualiaStructure"/>
 *               &lt;enumeration value="syntacticoSemanticLinks"/>
 *               &lt;enumeration value="other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="conformanceToStandardsBestPractices" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}conformanceToStandardsBestPractices" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}theoreticModel" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="externalRef" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lexicalConceptualResourceEncodingInfoType", propOrder = {
    "contentTypes",
    "conformanceToStandardsBestPractices",
    "theoreticModel",
    "externalRef"
})
public class LexicalConceptualResourceEncodingInfoType {

    @XmlElement(required = true)
    protected List<String> contentTypes;
    @XmlSchemaType(name = "string")
    protected List<ConformanceToStandardsBestPractices> conformanceToStandardsBestPractices;
    protected List<String> theoreticModel;
    protected List<String> externalRef;

    /**
     * Gets the value of the contentTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contentTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContentTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getContentTypes() {
        if (contentTypes == null) {
            contentTypes = new ArrayList<String>();
        }
        return this.contentTypes;
    }

    /**
     * Gets the value of the conformanceToStandardsBestPractices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conformanceToStandardsBestPractices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConformanceToStandardsBestPractices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConformanceToStandardsBestPractices }
     * 
     * 
     */
    public List<ConformanceToStandardsBestPractices> getConformanceToStandardsBestPractices() {
        if (conformanceToStandardsBestPractices == null) {
            conformanceToStandardsBestPractices = new ArrayList<ConformanceToStandardsBestPractices>();
        }
        return this.conformanceToStandardsBestPractices;
    }

    /**
     * Gets the value of the theoreticModel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the theoreticModel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTheoreticModel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTheoreticModel() {
        if (theoreticModel == null) {
            theoreticModel = new ArrayList<String>();
        }
        return this.theoreticModel;
    }

    /**
     * Gets the value of the externalRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getExternalRef() {
        if (externalRef == null) {
            externalRef = new ArrayList<String>();
        }
        return this.externalRef;
    }

}
