//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 12:36:44 PM CET 
//


package io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for licenceInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="licenceInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="licence">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *               &lt;enumeration value="CC-BY-4.0"/>
 *               &lt;enumeration value="CC-BY-NC-4.0"/>
 *               &lt;enumeration value="CC-BY-NC-ND-4.0"/>
 *               &lt;enumeration value="CC-BY-NC-SA-4.0"/>
 *               &lt;enumeration value="CC-BY-ND-4.0"/>
 *               &lt;enumeration value="CC-BY-SA-4.0"/>
 *               &lt;enumeration value="CC0-1.0"/>
 *               &lt;enumeration value="CC-BY-3.0"/>
 *               &lt;enumeration value="CC-BY-NC-3.0"/>
 *               &lt;enumeration value="CC-BY-NC-ND-3.0"/>
 *               &lt;enumeration value="CC-BY-NC-SA-3.0"/>
 *               &lt;enumeration value="CC-BY-ND-3.0"/>
 *               &lt;enumeration value="CC-BY-SA-3.0"/>
 *               &lt;enumeration value="PDDL"/>
 *               &lt;enumeration value="ODC-BY-1.0"/>
 *               &lt;enumeration value="ODbL-1.0"/>
 *               &lt;enumeration value="AGPL-1.0"/>
 *               &lt;enumeration value="Apache-2.0"/>
 *               &lt;enumeration value="BSD-4-Clause"/>
 *               &lt;enumeration value="BSD-3-Clause"/>
 *               &lt;enumeration value="BSD-2-Clause"/>
 *               &lt;enumeration value="GFDL-1.3"/>
 *               &lt;enumeration value="GPL-3.0"/>
 *               &lt;enumeration value="LGPL-3.0"/>
 *               &lt;enumeration value="MIT"/>
 *               &lt;enumeration value="Princeton-WordNet"/>
 *               &lt;enumeration value="EPL-1.0"/>
 *               &lt;enumeration value="NLM"/>
 *               &lt;enumeration value="f-DPPL-3.0"/>
 *               &lt;enumeration value="M-DPPL-3.0"/>
 *               &lt;enumeration value="proprietary"/>
 *               &lt;enumeration value="underNegotiation"/>
 *               &lt;enumeration value="openAccessUnspecified"/>
 *               &lt;enumeration value="restrictedAccessUnspecified"/>
 *               &lt;enumeration value="nonStandardLicenceTerms"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nonStandardLicenceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nonStandardLicenceTermsURL" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}httpURI" minOccurs="0"/>
 *         &lt;element name="nonStandaradLicenceTermsText" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;restriction base="&lt;http://www.meta-share.org/OMTD-SHARE_XMLSchema>myString">
 *               &lt;/restriction>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="conditionOfUse" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *               &lt;enumeration value="attribution"/>
 *               &lt;enumeration value="nonCommercialUse"/>
 *               &lt;enumeration value="commercialUse"/>
 *               &lt;enumeration value="shareAlike"/>
 *               &lt;enumeration value="noDerivatives"/>
 *               &lt;enumeration value="noRedistribution"/>
 *               &lt;enumeration value="evaluationUse"/>
 *               &lt;enumeration value="research"/>
 *               &lt;enumeration value="languageEngineeringResearch"/>
 *               &lt;enumeration value="education"/>
 *               &lt;enumeration value="informLicensor"/>
 *               &lt;enumeration value="redeposit"/>
 *               &lt;enumeration value="compensate"/>
 *               &lt;enumeration value="personalDataIncluded"/>
 *               &lt;enumeration value="sensitiveDataIncluded"/>
 *               &lt;enumeration value="requestPlan"/>
 *               &lt;enumeration value="spatialConstraint"/>
 *               &lt;enumeration value="userIdentified"/>
 *               &lt;enumeration value="academicUsers"/>
 *               &lt;enumeration value="commercialUsers"/>
 *               &lt;enumeration value="membersOfGroup"/>
 *               &lt;enumeration value="other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "licenceInfoType", propOrder = {
    "licence",
    "nonStandardLicenceName",
    "nonStandardLicenceTermsURL",
    "nonStandaradLicenceTermsText",
    "conditionOfUse"
})
public class LicenceInfoType {

    @XmlElement(required = true)
    protected String licence;
    protected String nonStandardLicenceName;
    @XmlSchemaType(name = "anyURI")
    protected String nonStandardLicenceTermsURL;
    protected List<LicenceInfoType.NonStandaradLicenceTermsText> nonStandaradLicenceTermsText;
    protected List<String> conditionOfUse;

    /**
     * Gets the value of the licence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicence() {
        return licence;
    }

    /**
     * Sets the value of the licence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicence(String value) {
        this.licence = value;
    }

    /**
     * Gets the value of the nonStandardLicenceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonStandardLicenceName() {
        return nonStandardLicenceName;
    }

    /**
     * Sets the value of the nonStandardLicenceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonStandardLicenceName(String value) {
        this.nonStandardLicenceName = value;
    }

    /**
     * Gets the value of the nonStandardLicenceTermsURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonStandardLicenceTermsURL() {
        return nonStandardLicenceTermsURL;
    }

    /**
     * Sets the value of the nonStandardLicenceTermsURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonStandardLicenceTermsURL(String value) {
        this.nonStandardLicenceTermsURL = value;
    }

    /**
     * Gets the value of the nonStandaradLicenceTermsText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nonStandaradLicenceTermsText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNonStandaradLicenceTermsText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LicenceInfoType.NonStandaradLicenceTermsText }
     * 
     * 
     */
    public List<LicenceInfoType.NonStandaradLicenceTermsText> getNonStandaradLicenceTermsText() {
        if (nonStandaradLicenceTermsText == null) {
            nonStandaradLicenceTermsText = new ArrayList<LicenceInfoType.NonStandaradLicenceTermsText>();
        }
        return this.nonStandaradLicenceTermsText;
    }

    /**
     * Gets the value of the conditionOfUse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conditionOfUse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConditionOfUse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getConditionOfUse() {
        if (conditionOfUse == null) {
            conditionOfUse = new ArrayList<String>();
        }
        return this.conditionOfUse;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;restriction base="&lt;http://www.meta-share.org/OMTD-SHARE_XMLSchema>myString">
     *     &lt;/restriction>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class NonStandaradLicenceTermsText
        extends MyString
    {


    }

}
