//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 12:36:44 PM CET 
//


package io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lingualityInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lingualityInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lingualityType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *               &lt;enumeration value="monolingual"/>
 *               &lt;enumeration value="bilingual"/>
 *               &lt;enumeration value="multilingual"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="multilingualityType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="parallel"/>
 *               &lt;enumeration value="comparable"/>
 *               &lt;enumeration value="multilingualSingleText"/>
 *               &lt;enumeration value="originalTranslationsInSameText"/>
 *               &lt;enumeration value="other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="multilingualityTypeDetails" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="512"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lingualityInfoType", propOrder = {
    "lingualityType",
    "multilingualityType",
    "multilingualityTypeDetails"
})
public class LingualityInfoType {

    @XmlElement(required = true)
    protected String lingualityType;
    protected String multilingualityType;
    protected String multilingualityTypeDetails;

    /**
     * Gets the value of the lingualityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLingualityType() {
        return lingualityType;
    }

    /**
     * Sets the value of the lingualityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLingualityType(String value) {
        this.lingualityType = value;
    }

    /**
     * Gets the value of the multilingualityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultilingualityType() {
        return multilingualityType;
    }

    /**
     * Sets the value of the multilingualityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultilingualityType(String value) {
        this.multilingualityType = value;
    }

    /**
     * Gets the value of the multilingualityTypeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultilingualityTypeDetails() {
        return multilingualityTypeDetails;
    }

    /**
     * Sets the value of the multilingualityTypeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultilingualityTypeDetails(String value) {
        this.multilingualityTypeDetails = value;
    }

}
