//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 12:36:44 PM CET 
//


package io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mailingListInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mailingListInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mailingListName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subscribe" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}emailAddress"/>
 *         &lt;element name="unsubscribe" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}emailAddress"/>
 *         &lt;element name="post" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}emailAddress"/>
 *         &lt;element name="archive" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}httpURI"/>
 *         &lt;element name="otherArchives" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="otherArchive" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}httpURI" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mailingListInfoType", propOrder = {
    "mailingListName",
    "subscribe",
    "unsubscribe",
    "post",
    "archive",
    "otherArchives"
})
public class MailingListInfoType {

    @XmlElement(required = true)
    protected String mailingListName;
    @XmlElement(required = true)
    protected String subscribe;
    @XmlElement(required = true)
    protected String unsubscribe;
    @XmlElement(required = true)
    protected String post;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String archive;
    protected MailingListInfoType.OtherArchives otherArchives;

    /**
     * Gets the value of the mailingListName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailingListName() {
        return mailingListName;
    }

    /**
     * Sets the value of the mailingListName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailingListName(String value) {
        this.mailingListName = value;
    }

    /**
     * Gets the value of the subscribe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscribe() {
        return subscribe;
    }

    /**
     * Sets the value of the subscribe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscribe(String value) {
        this.subscribe = value;
    }

    /**
     * Gets the value of the unsubscribe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnsubscribe() {
        return unsubscribe;
    }

    /**
     * Sets the value of the unsubscribe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnsubscribe(String value) {
        this.unsubscribe = value;
    }

    /**
     * Gets the value of the post property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPost() {
        return post;
    }

    /**
     * Sets the value of the post property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPost(String value) {
        this.post = value;
    }

    /**
     * Gets the value of the archive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchive() {
        return archive;
    }

    /**
     * Sets the value of the archive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchive(String value) {
        this.archive = value;
    }

    /**
     * Gets the value of the otherArchives property.
     * 
     * @return
     *     possible object is
     *     {@link MailingListInfoType.OtherArchives }
     *     
     */
    public MailingListInfoType.OtherArchives getOtherArchives() {
        return otherArchives;
    }

    /**
     * Sets the value of the otherArchives property.
     * 
     * @param value
     *     allowed object is
     *     {@link MailingListInfoType.OtherArchives }
     *     
     */
    public void setOtherArchives(MailingListInfoType.OtherArchives value) {
        this.otherArchives = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="otherArchive" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}httpURI" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "otherArchive"
    })
    public static class OtherArchives {

        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected List<String> otherArchive;

        /**
         * Gets the value of the otherArchive property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the otherArchive property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOtherArchive().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getOtherArchive() {
            if (otherArchive == null) {
                otherArchive = new ArrayList<String>();
            }
            return this.otherArchive;
        }

    }

}
