//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 12:36:44 PM CET 
//


package io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ModalityInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "modalityInfo");
    private final static QName _SizeInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "sizeInfo");
    private final static QName _Publisher_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "publisher");
    private final static QName _ComponentDistributionInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "componentDistributionInfo");
    private final static QName _CharacterEncoding_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "characterEncoding");
    private final static QName _ProjectIdentifier_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "projectIdentifier");
    private final static QName _ActualUseInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "actualUseInfo");
    private final static QName _StartDate_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "startDate");
    private final static QName _LexicalConceptualResourceTextInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "lexicalConceptualResourceTextInfo");
    private final static QName _TDMMethod_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "TDMMethod");
    private final static QName _DatasetDistributionInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "datasetDistributionInfo");
    private final static QName _Size_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "size");
    private final static QName _PublicationIdentifier_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "publicationIdentifier");
    private final static QName _MetalanguageInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "metalanguageInfo");
    private final static QName _DistributionMedium_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "distributionMedium");
    private final static QName _AttributionText_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "attributionText");
    private final static QName _VersionInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "versionInfo");
    private final static QName _MediaType_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "mediaType");
    private final static QName _DocumentDistributionInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "documentDistributionInfo");
    private final static QName _CreationInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "creationInfo");
    private final static QName _ModalityType_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "modalityType");
    private final static QName _SamplesLocation_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "samplesLocation");
    private final static QName _LexicalConceptualResourceEncodingInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "lexicalConceptualResourceEncodingInfo");
    private final static QName _RelationInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "relationInfo");
    private final static QName _StructuralEncodingInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "structuralEncodingInfo");
    private final static QName _LanguageVarietyInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "languageVarietyInfo");
    private final static QName _Keyword_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "keyword");
    private final static QName _CommunicationInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "communicationInfo");
    private final static QName _TimeCoverageInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "timeCoverageInfo");
    private final static QName _ProjectInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "projectInfo");
    private final static QName _MetadataHeaderInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "metadataHeaderInfo");
    private final static QName _AnnotationResource_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "annotationResource");
    private final static QName _OrganizationIdentifier_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "organizationIdentifier");
    private final static QName _TheoreticModel_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "theoreticModel");
    private final static QName _GeographicCoverageInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "geographicCoverageInfo");
    private final static QName _ValidationInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "validationInfo");
    private final static QName _MimeType_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "mimeType");
    private final static QName _Language_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "language");
    private final static QName _ApplicationOther_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "applicationOther");
    private final static QName _RightsStatement_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "rightsStatement");
    private final static QName _IdentificationInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "identificationInfo");
    private final static QName _RightsHolder_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "rightsHolder");
    private final static QName _Date_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "date");
    private final static QName _EndDate_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "endDate");
    private final static QName _ContactInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "contactInfo");
    private final static QName _EncodingLevel_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "encodingLevel");
    private final static QName _CopyrightStatement_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "copyrightStatement");
    private final static QName _PersonIdentifier_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "personIdentifier");
    private final static QName _CharacterEncodingInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "characterEncodingInfo");
    private final static QName _LanguageVarietyName_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "languageVarietyName");
    private final static QName _Typesystem_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "typesystem");
    private final static QName _UsageInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "usageInfo");
    private final static QName _HasOriginalSource_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "hasOriginalSource");
    private final static QName _OrganizationInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "organizationInfo");
    private final static QName _LicenceInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "licenceInfo");
    private final static QName _LanguageId_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "languageId");
    private final static QName _LanguageInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "languageInfo");
    private final static QName _TextFormatInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "textFormatInfo");
    private final static QName _Sex_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "sex");
    private final static QName _AnnotationInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "annotationInfo");
    private final static QName _RunningEnvironmentInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "runningEnvironmentInfo");
    private final static QName _JournalIdentifier_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "journalIdentifier");
    private final static QName _LexicalConceptualResourceInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "lexicalConceptualResourceInfo");
    private final static QName _DistributionLocation_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "distributionLocation");
    private final static QName _TextClassificationInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "textClassificationInfo");
    private final static QName _ResourceDocumentationInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "resourceDocumentationInfo");
    private final static QName _PersonInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "personInfo");
    private final static QName _AnnotationSchema_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "annotationSchema");
    private final static QName _LingualityInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "lingualityInfo");
    private final static QName _AvailabilityEndDate_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "availabilityEndDate");
    private final static QName _DateRange_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "dateRange");
    private final static QName _ResourceCreationInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "resourceCreationInfo");
    private final static QName _DomainInfo_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "domainInfo");
    private final static QName _AvailabilityStartDate_QNAME = new QName("http://www.meta-share.org/OMTD-SHARE_XMLSchema", "availabilityStartDate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RightsInfo }
     * 
     */
    public RightsInfo createRightsInfo() {
        return new RightsInfo();
    }

    /**
     * Create an instance of {@link GroupInfoType }
     * 
     */
    public GroupInfoType createGroupInfoType() {
        return new GroupInfoType();
    }

    /**
     * Create an instance of {@link GroupInfoType.GroupNames }
     * 
     */
    public GroupInfoType.GroupNames createGroupInfoTypeGroupNames() {
        return new GroupInfoType.GroupNames();
    }

    /**
     * Create an instance of {@link MailingListInfoType }
     * 
     */
    public MailingListInfoType createMailingListInfoType() {
        return new MailingListInfoType();
    }

    /**
     * Create an instance of {@link RelatedDocumentInfoType }
     * 
     */
    public RelatedDocumentInfoType createRelatedDocumentInfoType() {
        return new RelatedDocumentInfoType();
    }

    /**
     * Create an instance of {@link JournalInfoType }
     * 
     */
    public JournalInfoType createJournalInfoType() {
        return new JournalInfoType();
    }

    /**
     * Create an instance of {@link JournalInfoType.JournalTitles }
     * 
     */
    public JournalInfoType.JournalTitles createJournalInfoTypeJournalTitles() {
        return new JournalInfoType.JournalTitles();
    }

    /**
     * Create an instance of {@link RepositoryInfoType }
     * 
     */
    public RepositoryInfoType createRepositoryInfoType() {
        return new RepositoryInfoType();
    }

    /**
     * Create an instance of {@link RepositoryInfoType.RepositoryNames }
     * 
     */
    public RepositoryInfoType.RepositoryNames createRepositoryInfoTypeRepositoryNames() {
        return new RepositoryInfoType.RepositoryNames();
    }

    /**
     * Create an instance of {@link UsageInfoType }
     * 
     */
    public UsageInfoType createUsageInfoType() {
        return new UsageInfoType();
    }

    /**
     * Create an instance of {@link LicenceInfoType }
     * 
     */
    public LicenceInfoType createLicenceInfoType() {
        return new LicenceInfoType();
    }

    /**
     * Create an instance of {@link AnnotationInfoType }
     * 
     */
    public AnnotationInfoType createAnnotationInfoType() {
        return new AnnotationInfoType();
    }

    /**
     * Create an instance of {@link LexicalConceptualResourceInfoType }
     * 
     */
    public LexicalConceptualResourceInfoType createLexicalConceptualResourceInfoType() {
        return new LexicalConceptualResourceInfoType();
    }

    /**
     * Create an instance of {@link PersonInfoType }
     * 
     */
    public PersonInfoType createPersonInfoType() {
        return new PersonInfoType();
    }

    /**
     * Create an instance of {@link TextClassificationInfoType }
     * 
     */
    public TextClassificationInfoType createTextClassificationInfoType() {
        return new TextClassificationInfoType();
    }

    /**
     * Create an instance of {@link ResourceDocumentationInfoType }
     * 
     */
    public ResourceDocumentationInfoType createResourceDocumentationInfoType() {
        return new ResourceDocumentationInfoType();
    }

    /**
     * Create an instance of {@link ResourceCreationInfoType }
     * 
     */
    public ResourceCreationInfoType createResourceCreationInfoType() {
        return new ResourceCreationInfoType();
    }

    /**
     * Create an instance of {@link ActualUseInfoType }
     * 
     */
    public ActualUseInfoType createActualUseInfoType() {
        return new ActualUseInfoType();
    }

    /**
     * Create an instance of {@link ComponentDistributionInfoType }
     * 
     */
    public ComponentDistributionInfoType createComponentDistributionInfoType() {
        return new ComponentDistributionInfoType();
    }

    /**
     * Create an instance of {@link OrganizationInfoType }
     * 
     */
    public OrganizationInfoType createOrganizationInfoType() {
        return new OrganizationInfoType();
    }

    /**
     * Create an instance of {@link OrganizationInfoType.DepartmentNames }
     * 
     */
    public OrganizationInfoType.DepartmentNames createOrganizationInfoTypeDepartmentNames() {
        return new OrganizationInfoType.DepartmentNames();
    }

    /**
     * Create an instance of {@link OrganizationInfoType.OrganizationAlternativeNames }
     * 
     */
    public OrganizationInfoType.OrganizationAlternativeNames createOrganizationInfoTypeOrganizationAlternativeNames() {
        return new OrganizationInfoType.OrganizationAlternativeNames();
    }

    /**
     * Create an instance of {@link OrganizationInfoType.OrganizationNames }
     * 
     */
    public OrganizationInfoType.OrganizationNames createOrganizationInfoTypeOrganizationNames() {
        return new OrganizationInfoType.OrganizationNames();
    }

    /**
     * Create an instance of {@link LanguageInfoType }
     * 
     */
    public LanguageInfoType createLanguageInfoType() {
        return new LanguageInfoType();
    }

    /**
     * Create an instance of {@link LexicalConceptualResourceTextInfoType }
     * 
     */
    public LexicalConceptualResourceTextInfoType createLexicalConceptualResourceTextInfoType() {
        return new LexicalConceptualResourceTextInfoType();
    }

    /**
     * Create an instance of {@link DatasetDistributionInfoType }
     * 
     */
    public DatasetDistributionInfoType createDatasetDistributionInfoType() {
        return new DatasetDistributionInfoType();
    }

    /**
     * Create an instance of {@link CreationInfoType }
     * 
     */
    public CreationInfoType createCreationInfoType() {
        return new CreationInfoType();
    }

    /**
     * Create an instance of {@link DocumentDistributionInfoType }
     * 
     */
    public DocumentDistributionInfoType createDocumentDistributionInfoType() {
        return new DocumentDistributionInfoType();
    }

    /**
     * Create an instance of {@link StructuralEncodingInfoType }
     * 
     */
    public StructuralEncodingInfoType createStructuralEncodingInfoType() {
        return new StructuralEncodingInfoType();
    }

    /**
     * Create an instance of {@link RelatedResourceType }
     * 
     */
    public RelatedResourceType createRelatedResourceType() {
        return new RelatedResourceType();
    }

    /**
     * Create an instance of {@link MetadataHeaderInfoType }
     * 
     */
    public MetadataHeaderInfoType createMetadataHeaderInfoType() {
        return new MetadataHeaderInfoType();
    }

    /**
     * Create an instance of {@link MetadataHeaderInfoType.SourceOfMetadataRecord }
     * 
     */
    public MetadataHeaderInfoType.SourceOfMetadataRecord createMetadataHeaderInfoTypeSourceOfMetadataRecord() {
        return new MetadataHeaderInfoType.SourceOfMetadataRecord();
    }

    /**
     * Create an instance of {@link ProjectInfoType }
     * 
     */
    public ProjectInfoType createProjectInfoType() {
        return new ProjectInfoType();
    }

    /**
     * Create an instance of {@link ProjectInfoType.ProjectShortNames }
     * 
     */
    public ProjectInfoType.ProjectShortNames createProjectInfoTypeProjectShortNames() {
        return new ProjectInfoType.ProjectShortNames();
    }

    /**
     * Create an instance of {@link ProjectInfoType.ProjectNames }
     * 
     */
    public ProjectInfoType.ProjectNames createProjectInfoTypeProjectNames() {
        return new ProjectInfoType.ProjectNames();
    }

    /**
     * Create an instance of {@link CommunicationInfoType }
     * 
     */
    public CommunicationInfoType createCommunicationInfoType() {
        return new CommunicationInfoType();
    }

    /**
     * Create an instance of {@link ValidationInfoType }
     * 
     */
    public ValidationInfoType createValidationInfoType() {
        return new ValidationInfoType();
    }

    /**
     * Create an instance of {@link ContactInfoType }
     * 
     */
    public ContactInfoType createContactInfoType() {
        return new ContactInfoType();
    }

    /**
     * Create an instance of {@link IdentificationInfoType }
     * 
     */
    public IdentificationInfoType createIdentificationInfoType() {
        return new IdentificationInfoType();
    }

    /**
     * Create an instance of {@link IdentificationInfoType.Descriptions }
     * 
     */
    public IdentificationInfoType.Descriptions createIdentificationInfoTypeDescriptions() {
        return new IdentificationInfoType.Descriptions();
    }

    /**
     * Create an instance of {@link ActorInfoType }
     * 
     */
    public ActorInfoType createActorInfoType() {
        return new ActorInfoType();
    }

    /**
     * Create an instance of {@link DateType }
     * 
     */
    public DateType createDateType() {
        return new DateType();
    }

    /**
     * Create an instance of {@link Subject }
     * 
     */
    public Subject createSubject() {
        return new Subject();
    }

    /**
     * Create an instance of {@link DataFormatInfo }
     * 
     */
    public DataFormatInfo createDataFormatInfo() {
        return new DataFormatInfo();
    }

    /**
     * Create an instance of {@link GeographicCoverageInfoType }
     * 
     */
    public GeographicCoverageInfoType createGeographicCoverageInfoType() {
        return new GeographicCoverageInfoType();
    }

    /**
     * Create an instance of {@link TimeCoverageInfoType }
     * 
     */
    public TimeCoverageInfoType createTimeCoverageInfoType() {
        return new TimeCoverageInfoType();
    }

    /**
     * Create an instance of {@link OrganizationIdentifierType }
     * 
     */
    public OrganizationIdentifierType createOrganizationIdentifierType() {
        return new OrganizationIdentifierType();
    }

    /**
     * Create an instance of {@link TextGenre }
     * 
     */
    public TextGenre createTextGenre() {
        return new TextGenre();
    }

    /**
     * Create an instance of {@link LexicalConceptualResourceEncodingInfoType }
     * 
     */
    public LexicalConceptualResourceEncodingInfoType createLexicalConceptualResourceEncodingInfoType() {
        return new LexicalConceptualResourceEncodingInfoType();
    }

    /**
     * Create an instance of {@link LanguageVarietyInfoType }
     * 
     */
    public LanguageVarietyInfoType createLanguageVarietyInfoType() {
        return new LanguageVarietyInfoType();
    }

    /**
     * Create an instance of {@link RelationInfoType }
     * 
     */
    public RelationInfoType createRelationInfoType() {
        return new RelationInfoType();
    }

    /**
     * Create an instance of {@link AnnotationTypeInfo }
     * 
     */
    public AnnotationTypeInfo createAnnotationTypeInfo() {
        return new AnnotationTypeInfo();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link ResourceName }
     * 
     */
    public ResourceName createResourceName() {
        return new ResourceName();
    }

    /**
     * Create an instance of {@link MyString }
     * 
     */
    public MyString createMyString() {
        return new MyString();
    }

    /**
     * Create an instance of {@link VersionInfoType }
     * 
     */
    public VersionInfoType createVersionInfoType() {
        return new VersionInfoType();
    }

    /**
     * Create an instance of {@link Domain }
     * 
     */
    public Domain createDomain() {
        return new Domain();
    }

    /**
     * Create an instance of {@link PublicationIdentifierType }
     * 
     */
    public PublicationIdentifierType createPublicationIdentifierType() {
        return new PublicationIdentifierType();
    }

    /**
     * Create an instance of {@link ModalityInfoType }
     * 
     */
    public ModalityInfoType createModalityInfoType() {
        return new ModalityInfoType();
    }

    /**
     * Create an instance of {@link SizeInfoType }
     * 
     */
    public SizeInfoType createSizeInfoType() {
        return new SizeInfoType();
    }

    /**
     * Create an instance of {@link ProjectIdentifierType }
     * 
     */
    public ProjectIdentifierType createProjectIdentifierType() {
        return new ProjectIdentifierType();
    }

    /**
     * Create an instance of {@link LingualityInfoType }
     * 
     */
    public LingualityInfoType createLingualityInfoType() {
        return new LingualityInfoType();
    }

    /**
     * Create an instance of {@link DomainInfoType }
     * 
     */
    public DomainInfoType createDomainInfoType() {
        return new DomainInfoType();
    }

    /**
     * Create an instance of {@link DateRangeType }
     * 
     */
    public DateRangeType createDateRangeType() {
        return new DateRangeType();
    }

    /**
     * Create an instance of {@link RunningEnvironmentInfoType }
     * 
     */
    public RunningEnvironmentInfoType createRunningEnvironmentInfoType() {
        return new RunningEnvironmentInfoType();
    }

    /**
     * Create an instance of {@link JournalIdentifierType }
     * 
     */
    public JournalIdentifierType createJournalIdentifierType() {
        return new JournalIdentifierType();
    }

    /**
     * Create an instance of {@link TextFormatInfoType }
     * 
     */
    public TextFormatInfoType createTextFormatInfoType() {
        return new TextFormatInfoType();
    }

    /**
     * Create an instance of {@link ResourceIdentifierType }
     * 
     */
    public ResourceIdentifierType createResourceIdentifierType() {
        return new ResourceIdentifierType();
    }

    /**
     * Create an instance of {@link RightsInfo.LicenceInfos }
     * 
     */
    public RightsInfo.LicenceInfos createRightsInfoLicenceInfos() {
        return new RightsInfo.LicenceInfos();
    }

    /**
     * Create an instance of {@link RightsInfo.RightsHolders }
     * 
     */
    public RightsInfo.RightsHolders createRightsInfoRightsHolders() {
        return new RightsInfo.RightsHolders();
    }

    /**
     * Create an instance of {@link DistributionLoc }
     * 
     */
    public DistributionLoc createDistributionLoc() {
        return new DistributionLoc();
    }

    /**
     * Create an instance of {@link PersonIdentifierType }
     * 
     */
    public PersonIdentifierType createPersonIdentifierType() {
        return new PersonIdentifierType();
    }

    /**
     * Create an instance of {@link CharacterEncodingInfoType }
     * 
     */
    public CharacterEncodingInfoType createCharacterEncodingInfoType() {
        return new CharacterEncodingInfoType();
    }

    /**
     * Create an instance of {@link Register }
     * 
     */
    public Register createRegister() {
        return new Register();
    }

    /**
     * Create an instance of {@link LcrMetadataRecord }
     * 
     */
    public LcrMetadataRecord createLcrMetadataRecord() {
        return new LcrMetadataRecord();
    }

    /**
     * Create an instance of {@link BaseMetadataRecord }
     * 
     */
    public BaseMetadataRecord createBaseMetadataRecord() {
        return new BaseMetadataRecord();
    }

    /**
     * Create an instance of {@link DateCombinationType }
     * 
     */
    public DateCombinationType createDateCombinationType() {
        return new DateCombinationType();
    }

    /**
     * Create an instance of {@link MetadataIdentifierType }
     * 
     */
    public MetadataIdentifierType createMetadataIdentifierType() {
        return new MetadataIdentifierType();
    }

    /**
     * Create an instance of {@link RepositoryIdentifierType }
     * 
     */
    public RepositoryIdentifierType createRepositoryIdentifierType() {
        return new RepositoryIdentifierType();
    }

    /**
     * Create an instance of {@link GroupInfoType.GroupNames.GroupName }
     * 
     */
    public GroupInfoType.GroupNames.GroupName createGroupInfoTypeGroupNamesGroupName() {
        return new GroupInfoType.GroupNames.GroupName();
    }

    /**
     * Create an instance of {@link MailingListInfoType.OtherArchives }
     * 
     */
    public MailingListInfoType.OtherArchives createMailingListInfoTypeOtherArchives() {
        return new MailingListInfoType.OtherArchives();
    }

    /**
     * Create an instance of {@link RelatedDocumentInfoType.PublicationIdentifiers }
     * 
     */
    public RelatedDocumentInfoType.PublicationIdentifiers createRelatedDocumentInfoTypePublicationIdentifiers() {
        return new RelatedDocumentInfoType.PublicationIdentifiers();
    }

    /**
     * Create an instance of {@link JournalInfoType.Identifiers }
     * 
     */
    public JournalInfoType.Identifiers createJournalInfoTypeIdentifiers() {
        return new JournalInfoType.Identifiers();
    }

    /**
     * Create an instance of {@link JournalInfoType.Languages }
     * 
     */
    public JournalInfoType.Languages createJournalInfoTypeLanguages() {
        return new JournalInfoType.Languages();
    }

    /**
     * Create an instance of {@link JournalInfoType.Subjects }
     * 
     */
    public JournalInfoType.Subjects createJournalInfoTypeSubjects() {
        return new JournalInfoType.Subjects();
    }

    /**
     * Create an instance of {@link JournalInfoType.Rights }
     * 
     */
    public JournalInfoType.Rights createJournalInfoTypeRights() {
        return new JournalInfoType.Rights();
    }

    /**
     * Create an instance of {@link JournalInfoType.JournalTitles.JournalTitle }
     * 
     */
    public JournalInfoType.JournalTitles.JournalTitle createJournalInfoTypeJournalTitlesJournalTitle() {
        return new JournalInfoType.JournalTitles.JournalTitle();
    }

    /**
     * Create an instance of {@link RepositoryInfoType.RepositoryIdentifiers }
     * 
     */
    public RepositoryInfoType.RepositoryIdentifiers createRepositoryInfoTypeRepositoryIdentifiers() {
        return new RepositoryInfoType.RepositoryIdentifiers();
    }

    /**
     * Create an instance of {@link RepositoryInfoType.RepositoryNames.RepositoryName }
     * 
     */
    public RepositoryInfoType.RepositoryNames.RepositoryName createRepositoryInfoTypeRepositoryNamesRepositoryName() {
        return new RepositoryInfoType.RepositoryNames.RepositoryName();
    }

    /**
     * Create an instance of {@link UsageInfoType.IntendedApplications }
     * 
     */
    public UsageInfoType.IntendedApplications createUsageInfoTypeIntendedApplications() {
        return new UsageInfoType.IntendedApplications();
    }

    /**
     * Create an instance of {@link UsageInfoType.ActualUseInfos }
     * 
     */
    public UsageInfoType.ActualUseInfos createUsageInfoTypeActualUseInfos() {
        return new UsageInfoType.ActualUseInfos();
    }

    /**
     * Create an instance of {@link LicenceInfoType.NonStandaradLicenceTermsText }
     * 
     */
    public LicenceInfoType.NonStandaradLicenceTermsText createLicenceInfoTypeNonStandaradLicenceTermsText() {
        return new LicenceInfoType.NonStandaradLicenceTermsText();
    }

    /**
     * Create an instance of {@link AnnotationInfoType.AnnotationTypes }
     * 
     */
    public AnnotationInfoType.AnnotationTypes createAnnotationInfoTypeAnnotationTypes() {
        return new AnnotationInfoType.AnnotationTypes();
    }

    /**
     * Create an instance of {@link AnnotationInfoType.Annotators }
     * 
     */
    public AnnotationInfoType.Annotators createAnnotationInfoTypeAnnotators() {
        return new AnnotationInfoType.Annotators();
    }

    /**
     * Create an instance of {@link LexicalConceptualResourceInfoType.DistributionInfos }
     * 
     */
    public LexicalConceptualResourceInfoType.DistributionInfos createLexicalConceptualResourceInfoTypeDistributionInfos() {
        return new LexicalConceptualResourceInfoType.DistributionInfos();
    }

    /**
     * Create an instance of {@link LexicalConceptualResourceInfoType.ResourceDocumentations }
     * 
     */
    public LexicalConceptualResourceInfoType.ResourceDocumentations createLexicalConceptualResourceInfoTypeResourceDocumentations() {
        return new LexicalConceptualResourceInfoType.ResourceDocumentations();
    }

    /**
     * Create an instance of {@link LexicalConceptualResourceInfoType.ValidationInfos }
     * 
     */
    public LexicalConceptualResourceInfoType.ValidationInfos createLexicalConceptualResourceInfoTypeValidationInfos() {
        return new LexicalConceptualResourceInfoType.ValidationInfos();
    }

    /**
     * Create an instance of {@link LexicalConceptualResourceInfoType.Relations }
     * 
     */
    public LexicalConceptualResourceInfoType.Relations createLexicalConceptualResourceInfoTypeRelations() {
        return new LexicalConceptualResourceInfoType.Relations();
    }

    /**
     * Create an instance of {@link PersonInfoType.PersonIdentifiers }
     * 
     */
    public PersonInfoType.PersonIdentifiers createPersonInfoTypePersonIdentifiers() {
        return new PersonInfoType.PersonIdentifiers();
    }

    /**
     * Create an instance of {@link PersonInfoType.Affiliation }
     * 
     */
    public PersonInfoType.Affiliation createPersonInfoTypeAffiliation() {
        return new PersonInfoType.Affiliation();
    }

    /**
     * Create an instance of {@link TextClassificationInfoType.Keywords }
     * 
     */
    public TextClassificationInfoType.Keywords createTextClassificationInfoTypeKeywords() {
        return new TextClassificationInfoType.Keywords();
    }

    /**
     * Create an instance of {@link ResourceDocumentationInfoType.PublicationIdentifiers }
     * 
     */
    public ResourceDocumentationInfoType.PublicationIdentifiers createResourceDocumentationInfoTypePublicationIdentifiers() {
        return new ResourceDocumentationInfoType.PublicationIdentifiers();
    }

    /**
     * Create an instance of {@link ResourceCreationInfoType.ResourceCreators }
     * 
     */
    public ResourceCreationInfoType.ResourceCreators createResourceCreationInfoTypeResourceCreators() {
        return new ResourceCreationInfoType.ResourceCreators();
    }

    /**
     * Create an instance of {@link ResourceCreationInfoType.FundingProjects }
     * 
     */
    public ResourceCreationInfoType.FundingProjects createResourceCreationInfoTypeFundingProjects() {
        return new ResourceCreationInfoType.FundingProjects();
    }

    /**
     * Create an instance of {@link ActualUseInfoType.ApplicationsInvolved }
     * 
     */
    public ActualUseInfoType.ApplicationsInvolved createActualUseInfoTypeApplicationsInvolved() {
        return new ActualUseInfoType.ApplicationsInvolved();
    }

    /**
     * Create an instance of {@link ActualUseInfoType.UsageReports }
     * 
     */
    public ActualUseInfoType.UsageReports createActualUseInfoTypeUsageReports() {
        return new ActualUseInfoType.UsageReports();
    }

    /**
     * Create an instance of {@link ActualUseInfoType.DerivedResources }
     * 
     */
    public ActualUseInfoType.DerivedResources createActualUseInfoTypeDerivedResources() {
        return new ActualUseInfoType.DerivedResources();
    }

    /**
     * Create an instance of {@link ActualUseInfoType.UsageProjects }
     * 
     */
    public ActualUseInfoType.UsageProjects createActualUseInfoTypeUsageProjects() {
        return new ActualUseInfoType.UsageProjects();
    }

    /**
     * Create an instance of {@link ComponentDistributionInfoType.OperatingSystems }
     * 
     */
    public ComponentDistributionInfoType.OperatingSystems createComponentDistributionInfoTypeOperatingSystems() {
        return new ComponentDistributionInfoType.OperatingSystems();
    }

    /**
     * Create an instance of {@link OrganizationInfoType.OrganizationIdentifiers }
     * 
     */
    public OrganizationInfoType.OrganizationIdentifiers createOrganizationInfoTypeOrganizationIdentifiers() {
        return new OrganizationInfoType.OrganizationIdentifiers();
    }

    /**
     * Create an instance of {@link OrganizationInfoType.DepartmentNames.DepartmentName }
     * 
     */
    public OrganizationInfoType.DepartmentNames.DepartmentName createOrganizationInfoTypeDepartmentNamesDepartmentName() {
        return new OrganizationInfoType.DepartmentNames.DepartmentName();
    }

    /**
     * Create an instance of {@link OrganizationInfoType.OrganizationAlternativeNames.OrganizationAlternativeName }
     * 
     */
    public OrganizationInfoType.OrganizationAlternativeNames.OrganizationAlternativeName createOrganizationInfoTypeOrganizationAlternativeNamesOrganizationAlternativeName() {
        return new OrganizationInfoType.OrganizationAlternativeNames.OrganizationAlternativeName();
    }

    /**
     * Create an instance of {@link OrganizationInfoType.OrganizationNames.OrganizationName }
     * 
     */
    public OrganizationInfoType.OrganizationNames.OrganizationName createOrganizationInfoTypeOrganizationNamesOrganizationName() {
        return new OrganizationInfoType.OrganizationNames.OrganizationName();
    }

    /**
     * Create an instance of {@link LanguageInfoType.LanguageVarieties }
     * 
     */
    public LanguageInfoType.LanguageVarieties createLanguageInfoTypeLanguageVarieties() {
        return new LanguageInfoType.LanguageVarieties();
    }

    /**
     * Create an instance of {@link LexicalConceptualResourceTextInfoType.Languages }
     * 
     */
    public LexicalConceptualResourceTextInfoType.Languages createLexicalConceptualResourceTextInfoTypeLanguages() {
        return new LexicalConceptualResourceTextInfoType.Languages();
    }

    /**
     * Create an instance of {@link LexicalConceptualResourceTextInfoType.Metalanguages }
     * 
     */
    public LexicalConceptualResourceTextInfoType.Metalanguages createLexicalConceptualResourceTextInfoTypeMetalanguages() {
        return new LexicalConceptualResourceTextInfoType.Metalanguages();
    }

    /**
     * Create an instance of {@link LexicalConceptualResourceTextInfoType.Domains }
     * 
     */
    public LexicalConceptualResourceTextInfoType.Domains createLexicalConceptualResourceTextInfoTypeDomains() {
        return new LexicalConceptualResourceTextInfoType.Domains();
    }

    /**
     * Create an instance of {@link LexicalConceptualResourceTextInfoType.Keywords }
     * 
     */
    public LexicalConceptualResourceTextInfoType.Keywords createLexicalConceptualResourceTextInfoTypeKeywords() {
        return new LexicalConceptualResourceTextInfoType.Keywords();
    }

    /**
     * Create an instance of {@link DatasetDistributionInfoType.Sizes }
     * 
     */
    public DatasetDistributionInfoType.Sizes createDatasetDistributionInfoTypeSizes() {
        return new DatasetDistributionInfoType.Sizes();
    }

    /**
     * Create an instance of {@link DatasetDistributionInfoType.TextFormats }
     * 
     */
    public DatasetDistributionInfoType.TextFormats createDatasetDistributionInfoTypeTextFormats() {
        return new DatasetDistributionInfoType.TextFormats();
    }

    /**
     * Create an instance of {@link DatasetDistributionInfoType.CharacterEncodings }
     * 
     */
    public DatasetDistributionInfoType.CharacterEncodings createDatasetDistributionInfoTypeCharacterEncodings() {
        return new DatasetDistributionInfoType.CharacterEncodings();
    }

    /**
     * Create an instance of {@link CreationInfoType.OriginalSources }
     * 
     */
    public CreationInfoType.OriginalSources createCreationInfoTypeOriginalSources() {
        return new CreationInfoType.OriginalSources();
    }

    /**
     * Create an instance of {@link CreationInfoType.CreationSwComponents }
     * 
     */
    public CreationInfoType.CreationSwComponents createCreationInfoTypeCreationSwComponents() {
        return new CreationInfoType.CreationSwComponents();
    }

    /**
     * Create an instance of {@link DocumentDistributionInfoType.Sizes }
     * 
     */
    public DocumentDistributionInfoType.Sizes createDocumentDistributionInfoTypeSizes() {
        return new DocumentDistributionInfoType.Sizes();
    }

    /**
     * Create an instance of {@link StructuralEncodingInfoType.StructuralEncoding }
     * 
     */
    public StructuralEncodingInfoType.StructuralEncoding createStructuralEncodingInfoTypeStructuralEncoding() {
        return new StructuralEncodingInfoType.StructuralEncoding();
    }

    /**
     * Create an instance of {@link RelatedResourceType.ResourceNames }
     * 
     */
    public RelatedResourceType.ResourceNames createRelatedResourceTypeResourceNames() {
        return new RelatedResourceType.ResourceNames();
    }

    /**
     * Create an instance of {@link RelatedResourceType.ResourceIdentifiers }
     * 
     */
    public RelatedResourceType.ResourceIdentifiers createRelatedResourceTypeResourceIdentifiers() {
        return new RelatedResourceType.ResourceIdentifiers();
    }

    /**
     * Create an instance of {@link MetadataHeaderInfoType.MetadataCreators }
     * 
     */
    public MetadataHeaderInfoType.MetadataCreators createMetadataHeaderInfoTypeMetadataCreators() {
        return new MetadataHeaderInfoType.MetadataCreators();
    }

    /**
     * Create an instance of {@link MetadataHeaderInfoType.SourceOfMetadataRecord.OriginalDataProviderInfo }
     * 
     */
    public MetadataHeaderInfoType.SourceOfMetadataRecord.OriginalDataProviderInfo createMetadataHeaderInfoTypeSourceOfMetadataRecordOriginalDataProviderInfo() {
        return new MetadataHeaderInfoType.SourceOfMetadataRecord.OriginalDataProviderInfo();
    }

    /**
     * Create an instance of {@link ProjectInfoType.ProjectIdentifiers }
     * 
     */
    public ProjectInfoType.ProjectIdentifiers createProjectInfoTypeProjectIdentifiers() {
        return new ProjectInfoType.ProjectIdentifiers();
    }

    /**
     * Create an instance of {@link ProjectInfoType.Webpages }
     * 
     */
    public ProjectInfoType.Webpages createProjectInfoTypeWebpages() {
        return new ProjectInfoType.Webpages();
    }

    /**
     * Create an instance of {@link ProjectInfoType.Funders }
     * 
     */
    public ProjectInfoType.Funders createProjectInfoTypeFunders() {
        return new ProjectInfoType.Funders();
    }

    /**
     * Create an instance of {@link ProjectInfoType.FundingTypes }
     * 
     */
    public ProjectInfoType.FundingTypes createProjectInfoTypeFundingTypes() {
        return new ProjectInfoType.FundingTypes();
    }

    /**
     * Create an instance of {@link ProjectInfoType.FundingCountries }
     * 
     */
    public ProjectInfoType.FundingCountries createProjectInfoTypeFundingCountries() {
        return new ProjectInfoType.FundingCountries();
    }

    /**
     * Create an instance of {@link ProjectInfoType.ProjectShortNames.ProjectShortName }
     * 
     */
    public ProjectInfoType.ProjectShortNames.ProjectShortName createProjectInfoTypeProjectShortNamesProjectShortName() {
        return new ProjectInfoType.ProjectShortNames.ProjectShortName();
    }

    /**
     * Create an instance of {@link ProjectInfoType.ProjectNames.ProjectName }
     * 
     */
    public ProjectInfoType.ProjectNames.ProjectName createProjectInfoTypeProjectNamesProjectName() {
        return new ProjectInfoType.ProjectNames.ProjectName();
    }

    /**
     * Create an instance of {@link CommunicationInfoType.Emails }
     * 
     */
    public CommunicationInfoType.Emails createCommunicationInfoTypeEmails() {
        return new CommunicationInfoType.Emails();
    }

    /**
     * Create an instance of {@link CommunicationInfoType.Homepages }
     * 
     */
    public CommunicationInfoType.Homepages createCommunicationInfoTypeHomepages() {
        return new CommunicationInfoType.Homepages();
    }

    /**
     * Create an instance of {@link CommunicationInfoType.PostalAddress }
     * 
     */
    public CommunicationInfoType.PostalAddress createCommunicationInfoTypePostalAddress() {
        return new CommunicationInfoType.PostalAddress();
    }

    /**
     * Create an instance of {@link CommunicationInfoType.TelephoneNumbers }
     * 
     */
    public CommunicationInfoType.TelephoneNumbers createCommunicationInfoTypeTelephoneNumbers() {
        return new CommunicationInfoType.TelephoneNumbers();
    }

    /**
     * Create an instance of {@link ValidationInfoType.ValidationReports }
     * 
     */
    public ValidationInfoType.ValidationReports createValidationInfoTypeValidationReports() {
        return new ValidationInfoType.ValidationReports();
    }

    /**
     * Create an instance of {@link ValidationInfoType.ValidationSwComponents }
     * 
     */
    public ValidationInfoType.ValidationSwComponents createValidationInfoTypeValidationSwComponents() {
        return new ValidationInfoType.ValidationSwComponents();
    }

    /**
     * Create an instance of {@link ValidationInfoType.Validators }
     * 
     */
    public ValidationInfoType.Validators createValidationInfoTypeValidators() {
        return new ValidationInfoType.Validators();
    }

    /**
     * Create an instance of {@link ContactInfoType.ContactPersons }
     * 
     */
    public ContactInfoType.ContactPersons createContactInfoTypeContactPersons() {
        return new ContactInfoType.ContactPersons();
    }

    /**
     * Create an instance of {@link ContactInfoType.ContactGroups }
     * 
     */
    public ContactInfoType.ContactGroups createContactInfoTypeContactGroups() {
        return new ContactInfoType.ContactGroups();
    }

    /**
     * Create an instance of {@link ContactInfoType.MailingLists }
     * 
     */
    public ContactInfoType.MailingLists createContactInfoTypeMailingLists() {
        return new ContactInfoType.MailingLists();
    }

    /**
     * Create an instance of {@link IdentificationInfoType.ResourceNames }
     * 
     */
    public IdentificationInfoType.ResourceNames createIdentificationInfoTypeResourceNames() {
        return new IdentificationInfoType.ResourceNames();
    }

    /**
     * Create an instance of {@link IdentificationInfoType.ResourceIdentifiers }
     * 
     */
    public IdentificationInfoType.ResourceIdentifiers createIdentificationInfoTypeResourceIdentifiers() {
        return new IdentificationInfoType.ResourceIdentifiers();
    }

    /**
     * Create an instance of {@link IdentificationInfoType.Descriptions.Description }
     * 
     */
    public IdentificationInfoType.Descriptions.Description createIdentificationInfoTypeDescriptionsDescription() {
        return new IdentificationInfoType.Descriptions.Description();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModalityInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "modalityInfo")
    public JAXBElement<ModalityInfoType> createModalityInfo(ModalityInfoType value) {
        return new JAXBElement<ModalityInfoType>(_ModalityInfo_QNAME, ModalityInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SizeInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "sizeInfo")
    public JAXBElement<SizeInfoType> createSizeInfo(SizeInfoType value) {
        return new JAXBElement<SizeInfoType>(_SizeInfo_QNAME, SizeInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganizationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "publisher")
    public JAXBElement<OrganizationInfoType> createPublisher(OrganizationInfoType value) {
        return new JAXBElement<OrganizationInfoType>(_Publisher_QNAME, OrganizationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComponentDistributionInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "componentDistributionInfo")
    public JAXBElement<ComponentDistributionInfoType> createComponentDistributionInfo(ComponentDistributionInfoType value) {
        return new JAXBElement<ComponentDistributionInfoType>(_ComponentDistributionInfo_QNAME, ComponentDistributionInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "characterEncoding")
    public JAXBElement<String> createCharacterEncoding(String value) {
        return new JAXBElement<String>(_CharacterEncoding_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProjectIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "projectIdentifier")
    public JAXBElement<ProjectIdentifierType> createProjectIdentifier(ProjectIdentifierType value) {
        return new JAXBElement<ProjectIdentifierType>(_ProjectIdentifier_QNAME, ProjectIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActualUseInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "actualUseInfo")
    public JAXBElement<ActualUseInfoType> createActualUseInfo(ActualUseInfoType value) {
        return new JAXBElement<ActualUseInfoType>(_ActualUseInfo_QNAME, ActualUseInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "startDate")
    public JAXBElement<DateType> createStartDate(DateType value) {
        return new JAXBElement<DateType>(_StartDate_QNAME, DateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LexicalConceptualResourceTextInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "lexicalConceptualResourceTextInfo")
    public JAXBElement<LexicalConceptualResourceTextInfoType> createLexicalConceptualResourceTextInfo(LexicalConceptualResourceTextInfoType value) {
        return new JAXBElement<LexicalConceptualResourceTextInfoType>(_LexicalConceptualResourceTextInfo_QNAME, LexicalConceptualResourceTextInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "TDMMethod")
    public JAXBElement<String> createTDMMethod(String value) {
        return new JAXBElement<String>(_TDMMethod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DatasetDistributionInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "datasetDistributionInfo")
    public JAXBElement<DatasetDistributionInfoType> createDatasetDistributionInfo(DatasetDistributionInfoType value) {
        return new JAXBElement<DatasetDistributionInfoType>(_DatasetDistributionInfo_QNAME, DatasetDistributionInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "size")
    public JAXBElement<String> createSize(String value) {
        return new JAXBElement<String>(_Size_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PublicationIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "publicationIdentifier")
    public JAXBElement<PublicationIdentifierType> createPublicationIdentifier(PublicationIdentifierType value) {
        return new JAXBElement<PublicationIdentifierType>(_PublicationIdentifier_QNAME, PublicationIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguageInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "metalanguageInfo")
    public JAXBElement<LanguageInfoType> createMetalanguageInfo(LanguageInfoType value) {
        return new JAXBElement<LanguageInfoType>(_MetalanguageInfo_QNAME, LanguageInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "distributionMedium")
    public JAXBElement<String> createDistributionMedium(String value) {
        return new JAXBElement<String>(_DistributionMedium_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "attributionText")
    public JAXBElement<String> createAttributionText(String value) {
        return new JAXBElement<String>(_AttributionText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VersionInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "versionInfo")
    public JAXBElement<VersionInfoType> createVersionInfo(VersionInfoType value) {
        return new JAXBElement<VersionInfoType>(_VersionInfo_QNAME, VersionInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "mediaType")
    public JAXBElement<String> createMediaType(String value) {
        return new JAXBElement<String>(_MediaType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentDistributionInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "documentDistributionInfo")
    public JAXBElement<DocumentDistributionInfoType> createDocumentDistributionInfo(DocumentDistributionInfoType value) {
        return new JAXBElement<DocumentDistributionInfoType>(_DocumentDistributionInfo_QNAME, DocumentDistributionInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "creationInfo")
    public JAXBElement<CreationInfoType> createCreationInfo(CreationInfoType value) {
        return new JAXBElement<CreationInfoType>(_CreationInfo_QNAME, CreationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "modalityType")
    public JAXBElement<String> createModalityType(String value) {
        return new JAXBElement<String>(_ModalityType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "samplesLocation")
    public JAXBElement<String> createSamplesLocation(String value) {
        return new JAXBElement<String>(_SamplesLocation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LexicalConceptualResourceEncodingInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "lexicalConceptualResourceEncodingInfo")
    public JAXBElement<LexicalConceptualResourceEncodingInfoType> createLexicalConceptualResourceEncodingInfo(LexicalConceptualResourceEncodingInfoType value) {
        return new JAXBElement<LexicalConceptualResourceEncodingInfoType>(_LexicalConceptualResourceEncodingInfo_QNAME, LexicalConceptualResourceEncodingInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "relationInfo")
    public JAXBElement<RelationInfoType> createRelationInfo(RelationInfoType value) {
        return new JAXBElement<RelationInfoType>(_RelationInfo_QNAME, RelationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StructuralEncodingInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "structuralEncodingInfo")
    public JAXBElement<StructuralEncodingInfoType> createStructuralEncodingInfo(StructuralEncodingInfoType value) {
        return new JAXBElement<StructuralEncodingInfoType>(_StructuralEncodingInfo_QNAME, StructuralEncodingInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguageVarietyInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "languageVarietyInfo")
    public JAXBElement<LanguageVarietyInfoType> createLanguageVarietyInfo(LanguageVarietyInfoType value) {
        return new JAXBElement<LanguageVarietyInfoType>(_LanguageVarietyInfo_QNAME, LanguageVarietyInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "keyword")
    public JAXBElement<String> createKeyword(String value) {
        return new JAXBElement<String>(_Keyword_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommunicationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "communicationInfo")
    public JAXBElement<CommunicationInfoType> createCommunicationInfo(CommunicationInfoType value) {
        return new JAXBElement<CommunicationInfoType>(_CommunicationInfo_QNAME, CommunicationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimeCoverageInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "timeCoverageInfo")
    public JAXBElement<TimeCoverageInfoType> createTimeCoverageInfo(TimeCoverageInfoType value) {
        return new JAXBElement<TimeCoverageInfoType>(_TimeCoverageInfo_QNAME, TimeCoverageInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProjectInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "projectInfo")
    public JAXBElement<ProjectInfoType> createProjectInfo(ProjectInfoType value) {
        return new JAXBElement<ProjectInfoType>(_ProjectInfo_QNAME, ProjectInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetadataHeaderInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "metadataHeaderInfo")
    public JAXBElement<MetadataHeaderInfoType> createMetadataHeaderInfo(MetadataHeaderInfoType value) {
        return new JAXBElement<MetadataHeaderInfoType>(_MetadataHeaderInfo_QNAME, MetadataHeaderInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelatedResourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "annotationResource")
    public JAXBElement<RelatedResourceType> createAnnotationResource(RelatedResourceType value) {
        return new JAXBElement<RelatedResourceType>(_AnnotationResource_QNAME, RelatedResourceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganizationIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "organizationIdentifier")
    public JAXBElement<OrganizationIdentifierType> createOrganizationIdentifier(OrganizationIdentifierType value) {
        return new JAXBElement<OrganizationIdentifierType>(_OrganizationIdentifier_QNAME, OrganizationIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "theoreticModel")
    public JAXBElement<String> createTheoreticModel(String value) {
        return new JAXBElement<String>(_TheoreticModel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeographicCoverageInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "geographicCoverageInfo")
    public JAXBElement<GeographicCoverageInfoType> createGeographicCoverageInfo(GeographicCoverageInfoType value) {
        return new JAXBElement<GeographicCoverageInfoType>(_GeographicCoverageInfo_QNAME, GeographicCoverageInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "validationInfo")
    public JAXBElement<ValidationInfoType> createValidationInfo(ValidationInfoType value) {
        return new JAXBElement<ValidationInfoType>(_ValidationInfo_QNAME, ValidationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "mimeType")
    public JAXBElement<String> createMimeType(String value) {
        return new JAXBElement<String>(_MimeType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguageIdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "language")
    public JAXBElement<LanguageIdType> createLanguage(LanguageIdType value) {
        return new JAXBElement<LanguageIdType>(_Language_QNAME, LanguageIdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "applicationOther")
    public JAXBElement<String> createApplicationOther(String value) {
        return new JAXBElement<String>(_ApplicationOther_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "rightsStatement")
    public JAXBElement<String> createRightsStatement(String value) {
        return new JAXBElement<String>(_RightsStatement_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "identificationInfo")
    public JAXBElement<IdentificationInfoType> createIdentificationInfo(IdentificationInfoType value) {
        return new JAXBElement<IdentificationInfoType>(_IdentificationInfo_QNAME, IdentificationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActorInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "rightsHolder")
    public JAXBElement<ActorInfoType> createRightsHolder(ActorInfoType value) {
        return new JAXBElement<ActorInfoType>(_RightsHolder_QNAME, ActorInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "date")
    public JAXBElement<DateType> createDate(DateType value) {
        return new JAXBElement<DateType>(_Date_QNAME, DateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "endDate")
    public JAXBElement<DateType> createEndDate(DateType value) {
        return new JAXBElement<DateType>(_EndDate_QNAME, DateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContactInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "contactInfo")
    public JAXBElement<ContactInfoType> createContactInfo(ContactInfoType value) {
        return new JAXBElement<ContactInfoType>(_ContactInfo_QNAME, ContactInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "encodingLevel")
    public JAXBElement<String> createEncodingLevel(String value) {
        return new JAXBElement<String>(_EncodingLevel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "copyrightStatement")
    public JAXBElement<String> createCopyrightStatement(String value) {
        return new JAXBElement<String>(_CopyrightStatement_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "personIdentifier")
    public JAXBElement<PersonIdentifierType> createPersonIdentifier(PersonIdentifierType value) {
        return new JAXBElement<PersonIdentifierType>(_PersonIdentifier_QNAME, PersonIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CharacterEncodingInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "characterEncodingInfo")
    public JAXBElement<CharacterEncodingInfoType> createCharacterEncodingInfo(CharacterEncodingInfoType value) {
        return new JAXBElement<CharacterEncodingInfoType>(_CharacterEncodingInfo_QNAME, CharacterEncodingInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "languageVarietyName")
    public JAXBElement<String> createLanguageVarietyName(String value) {
        return new JAXBElement<String>(_LanguageVarietyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelatedResourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "typesystem")
    public JAXBElement<RelatedResourceType> createTypesystem(RelatedResourceType value) {
        return new JAXBElement<RelatedResourceType>(_Typesystem_QNAME, RelatedResourceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UsageInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "usageInfo")
    public JAXBElement<UsageInfoType> createUsageInfo(UsageInfoType value) {
        return new JAXBElement<UsageInfoType>(_UsageInfo_QNAME, UsageInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "hasOriginalSource")
    public JAXBElement<ResourceIdentifierType> createHasOriginalSource(ResourceIdentifierType value) {
        return new JAXBElement<ResourceIdentifierType>(_HasOriginalSource_QNAME, ResourceIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganizationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "organizationInfo")
    public JAXBElement<OrganizationInfoType> createOrganizationInfo(OrganizationInfoType value) {
        return new JAXBElement<OrganizationInfoType>(_OrganizationInfo_QNAME, OrganizationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LicenceInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "licenceInfo")
    public JAXBElement<LicenceInfoType> createLicenceInfo(LicenceInfoType value) {
        return new JAXBElement<LicenceInfoType>(_LicenceInfo_QNAME, LicenceInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguageIdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "languageId")
    public JAXBElement<LanguageIdType> createLanguageId(LanguageIdType value) {
        return new JAXBElement<LanguageIdType>(_LanguageId_QNAME, LanguageIdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguageInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "languageInfo")
    public JAXBElement<LanguageInfoType> createLanguageInfo(LanguageInfoType value) {
        return new JAXBElement<LanguageInfoType>(_LanguageInfo_QNAME, LanguageInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextFormatInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "textFormatInfo")
    public JAXBElement<TextFormatInfoType> createTextFormatInfo(TextFormatInfoType value) {
        return new JAXBElement<TextFormatInfoType>(_TextFormatInfo_QNAME, TextFormatInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "sex")
    public JAXBElement<String> createSex(String value) {
        return new JAXBElement<String>(_Sex_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "annotationInfo")
    public JAXBElement<AnnotationInfoType> createAnnotationInfo(AnnotationInfoType value) {
        return new JAXBElement<AnnotationInfoType>(_AnnotationInfo_QNAME, AnnotationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RunningEnvironmentInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "runningEnvironmentInfo")
    public JAXBElement<RunningEnvironmentInfoType> createRunningEnvironmentInfo(RunningEnvironmentInfoType value) {
        return new JAXBElement<RunningEnvironmentInfoType>(_RunningEnvironmentInfo_QNAME, RunningEnvironmentInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JournalIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "journalIdentifier")
    public JAXBElement<JournalIdentifierType> createJournalIdentifier(JournalIdentifierType value) {
        return new JAXBElement<JournalIdentifierType>(_JournalIdentifier_QNAME, JournalIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LexicalConceptualResourceInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "lexicalConceptualResourceInfo")
    public JAXBElement<LexicalConceptualResourceInfoType> createLexicalConceptualResourceInfo(LexicalConceptualResourceInfoType value) {
        return new JAXBElement<LexicalConceptualResourceInfoType>(_LexicalConceptualResourceInfo_QNAME, LexicalConceptualResourceInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "distributionLocation")
    public JAXBElement<String> createDistributionLocation(String value) {
        return new JAXBElement<String>(_DistributionLocation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextClassificationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "textClassificationInfo")
    public JAXBElement<TextClassificationInfoType> createTextClassificationInfo(TextClassificationInfoType value) {
        return new JAXBElement<TextClassificationInfoType>(_TextClassificationInfo_QNAME, TextClassificationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceDocumentationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "resourceDocumentationInfo")
    public JAXBElement<ResourceDocumentationInfoType> createResourceDocumentationInfo(ResourceDocumentationInfoType value) {
        return new JAXBElement<ResourceDocumentationInfoType>(_ResourceDocumentationInfo_QNAME, ResourceDocumentationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "personInfo")
    public JAXBElement<PersonInfoType> createPersonInfo(PersonInfoType value) {
        return new JAXBElement<PersonInfoType>(_PersonInfo_QNAME, PersonInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelatedResourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "annotationSchema")
    public JAXBElement<RelatedResourceType> createAnnotationSchema(RelatedResourceType value) {
        return new JAXBElement<RelatedResourceType>(_AnnotationSchema_QNAME, RelatedResourceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LingualityInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "lingualityInfo")
    public JAXBElement<LingualityInfoType> createLingualityInfo(LingualityInfoType value) {
        return new JAXBElement<LingualityInfoType>(_LingualityInfo_QNAME, LingualityInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "availabilityEndDate")
    public JAXBElement<XMLGregorianCalendar> createAvailabilityEndDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AvailabilityEndDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateRangeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "dateRange")
    public JAXBElement<DateRangeType> createDateRange(DateRangeType value) {
        return new JAXBElement<DateRangeType>(_DateRange_QNAME, DateRangeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceCreationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "resourceCreationInfo")
    public JAXBElement<ResourceCreationInfoType> createResourceCreationInfo(ResourceCreationInfoType value) {
        return new JAXBElement<ResourceCreationInfoType>(_ResourceCreationInfo_QNAME, ResourceCreationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DomainInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "domainInfo")
    public JAXBElement<DomainInfoType> createDomainInfo(DomainInfoType value) {
        return new JAXBElement<DomainInfoType>(_DomainInfo_QNAME, DomainInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", name = "availabilityStartDate")
    public JAXBElement<XMLGregorianCalendar> createAvailabilityStartDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AvailabilityStartDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

}
