//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 12:36:44 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel;
