//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 12:36:44 PM CET 
//


package io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for projectInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="projectInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="projectNames">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="projectName" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;restriction base="&lt;http://www.meta-share.org/OMTD-SHARE_XMLSchema>myString">
 *                         &lt;/restriction>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="projectShortNames" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="projectShortName" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;restriction base="&lt;http://www.meta-share.org/OMTD-SHARE_XMLSchema>myString">
 *                         &lt;/restriction>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="projectIdentifiers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}projectIdentifier" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="webpages" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="webpage" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}httpURI" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="funders">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="funder" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}organizationInfoType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="fundingTypes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fundingType" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="30"/>
 *                         &lt;enumeration value="other"/>
 *                         &lt;enumeration value="ownFunds"/>
 *                         &lt;enumeration value="nationalFunds"/>
 *                         &lt;enumeration value="euFunds"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="fundingProgramme" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="jurisdiction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fundingCountries" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fundingCountry" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}regionIdType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="projectDates" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}dateCombinationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "projectInfoType", propOrder = {
    "projectNames",
    "projectShortNames",
    "projectIdentifiers",
    "webpages",
    "funders",
    "fundingTypes",
    "fundingProgramme",
    "jurisdiction",
    "fundingCountries",
    "projectDates"
})
public class ProjectInfoType {

    @XmlElement(required = true)
    protected ProjectInfoType.ProjectNames projectNames;
    protected ProjectInfoType.ProjectShortNames projectShortNames;
    protected ProjectInfoType.ProjectIdentifiers projectIdentifiers;
    protected ProjectInfoType.Webpages webpages;
    @XmlElement(required = true)
    protected ProjectInfoType.Funders funders;
    protected ProjectInfoType.FundingTypes fundingTypes;
    protected String fundingProgramme;
    protected String jurisdiction;
    protected ProjectInfoType.FundingCountries fundingCountries;
    protected DateCombinationType projectDates;

    /**
     * Gets the value of the projectNames property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectInfoType.ProjectNames }
     *     
     */
    public ProjectInfoType.ProjectNames getProjectNames() {
        return projectNames;
    }

    /**
     * Sets the value of the projectNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectInfoType.ProjectNames }
     *     
     */
    public void setProjectNames(ProjectInfoType.ProjectNames value) {
        this.projectNames = value;
    }

    /**
     * Gets the value of the projectShortNames property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectInfoType.ProjectShortNames }
     *     
     */
    public ProjectInfoType.ProjectShortNames getProjectShortNames() {
        return projectShortNames;
    }

    /**
     * Sets the value of the projectShortNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectInfoType.ProjectShortNames }
     *     
     */
    public void setProjectShortNames(ProjectInfoType.ProjectShortNames value) {
        this.projectShortNames = value;
    }

    /**
     * Gets the value of the projectIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectInfoType.ProjectIdentifiers }
     *     
     */
    public ProjectInfoType.ProjectIdentifiers getProjectIdentifiers() {
        return projectIdentifiers;
    }

    /**
     * Sets the value of the projectIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectInfoType.ProjectIdentifiers }
     *     
     */
    public void setProjectIdentifiers(ProjectInfoType.ProjectIdentifiers value) {
        this.projectIdentifiers = value;
    }

    /**
     * Gets the value of the webpages property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectInfoType.Webpages }
     *     
     */
    public ProjectInfoType.Webpages getWebpages() {
        return webpages;
    }

    /**
     * Sets the value of the webpages property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectInfoType.Webpages }
     *     
     */
    public void setWebpages(ProjectInfoType.Webpages value) {
        this.webpages = value;
    }

    /**
     * Gets the value of the funders property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectInfoType.Funders }
     *     
     */
    public ProjectInfoType.Funders getFunders() {
        return funders;
    }

    /**
     * Sets the value of the funders property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectInfoType.Funders }
     *     
     */
    public void setFunders(ProjectInfoType.Funders value) {
        this.funders = value;
    }

    /**
     * Gets the value of the fundingTypes property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectInfoType.FundingTypes }
     *     
     */
    public ProjectInfoType.FundingTypes getFundingTypes() {
        return fundingTypes;
    }

    /**
     * Sets the value of the fundingTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectInfoType.FundingTypes }
     *     
     */
    public void setFundingTypes(ProjectInfoType.FundingTypes value) {
        this.fundingTypes = value;
    }

    /**
     * Gets the value of the fundingProgramme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFundingProgramme() {
        return fundingProgramme;
    }

    /**
     * Sets the value of the fundingProgramme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFundingProgramme(String value) {
        this.fundingProgramme = value;
    }

    /**
     * Gets the value of the jurisdiction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJurisdiction() {
        return jurisdiction;
    }

    /**
     * Sets the value of the jurisdiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJurisdiction(String value) {
        this.jurisdiction = value;
    }

    /**
     * Gets the value of the fundingCountries property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectInfoType.FundingCountries }
     *     
     */
    public ProjectInfoType.FundingCountries getFundingCountries() {
        return fundingCountries;
    }

    /**
     * Sets the value of the fundingCountries property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectInfoType.FundingCountries }
     *     
     */
    public void setFundingCountries(ProjectInfoType.FundingCountries value) {
        this.fundingCountries = value;
    }

    /**
     * Gets the value of the projectDates property.
     * 
     * @return
     *     possible object is
     *     {@link DateCombinationType }
     *     
     */
    public DateCombinationType getProjectDates() {
        return projectDates;
    }

    /**
     * Sets the value of the projectDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCombinationType }
     *     
     */
    public void setProjectDates(DateCombinationType value) {
        this.projectDates = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="funder" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}organizationInfoType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "funder"
    })
    public static class Funders {

        @XmlElement(required = true)
        protected List<OrganizationInfoType> funder;

        /**
         * Gets the value of the funder property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the funder property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFunder().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OrganizationInfoType }
         * 
         * 
         */
        public List<OrganizationInfoType> getFunder() {
            if (funder == null) {
                funder = new ArrayList<OrganizationInfoType>();
            }
            return this.funder;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fundingCountry" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}regionIdType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fundingCountry"
    })
    public static class FundingCountries {

        protected List<String> fundingCountry;

        /**
         * Gets the value of the fundingCountry property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fundingCountry property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFundingCountry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getFundingCountry() {
            if (fundingCountry == null) {
                fundingCountry = new ArrayList<String>();
            }
            return this.fundingCountry;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fundingType" maxOccurs="unbounded" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="30"/>
     *               &lt;enumeration value="other"/>
     *               &lt;enumeration value="ownFunds"/>
     *               &lt;enumeration value="nationalFunds"/>
     *               &lt;enumeration value="euFunds"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fundingType"
    })
    public static class FundingTypes {

        protected List<String> fundingType;

        /**
         * Gets the value of the fundingType property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fundingType property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFundingType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getFundingType() {
            if (fundingType == null) {
                fundingType = new ArrayList<String>();
            }
            return this.fundingType;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}projectIdentifier" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "projectIdentifier"
    })
    public static class ProjectIdentifiers {

        @XmlElement(required = true)
        protected List<ProjectIdentifierType> projectIdentifier;

        /**
         * Gets the value of the projectIdentifier property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the projectIdentifier property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProjectIdentifier().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProjectIdentifierType }
         * 
         * 
         */
        public List<ProjectIdentifierType> getProjectIdentifier() {
            if (projectIdentifier == null) {
                projectIdentifier = new ArrayList<ProjectIdentifierType>();
            }
            return this.projectIdentifier;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="projectName" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;restriction base="&lt;http://www.meta-share.org/OMTD-SHARE_XMLSchema>myString">
     *               &lt;/restriction>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "projectName"
    })
    public static class ProjectNames {

        @XmlElement(required = true)
        protected List<ProjectInfoType.ProjectNames.ProjectName> projectName;

        /**
         * Gets the value of the projectName property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the projectName property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProjectName().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProjectInfoType.ProjectNames.ProjectName }
         * 
         * 
         */
        public List<ProjectInfoType.ProjectNames.ProjectName> getProjectName() {
            if (projectName == null) {
                projectName = new ArrayList<ProjectInfoType.ProjectNames.ProjectName>();
            }
            return this.projectName;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;restriction base="&lt;http://www.meta-share.org/OMTD-SHARE_XMLSchema>myString">
         *     &lt;/restriction>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class ProjectName
            extends MyString
        {


        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="projectShortName" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;restriction base="&lt;http://www.meta-share.org/OMTD-SHARE_XMLSchema>myString">
     *               &lt;/restriction>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "projectShortName"
    })
    public static class ProjectShortNames {

        protected List<ProjectInfoType.ProjectShortNames.ProjectShortName> projectShortName;

        /**
         * Gets the value of the projectShortName property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the projectShortName property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProjectShortName().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProjectInfoType.ProjectShortNames.ProjectShortName }
         * 
         * 
         */
        public List<ProjectInfoType.ProjectShortNames.ProjectShortName> getProjectShortName() {
            if (projectShortName == null) {
                projectShortName = new ArrayList<ProjectInfoType.ProjectShortNames.ProjectShortName>();
            }
            return this.projectShortName;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;restriction base="&lt;http://www.meta-share.org/OMTD-SHARE_XMLSchema>myString">
         *     &lt;/restriction>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class ProjectShortName
            extends MyString
        {


        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="webpage" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}httpURI" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "webpage"
    })
    public static class Webpages {

        @XmlSchemaType(name = "anyURI")
        protected List<String> webpage;

        /**
         * Gets the value of the webpage property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the webpage property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getWebpage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getWebpage() {
            if (webpage == null) {
                webpage = new ArrayList<String>();
            }
            return this.webpage;
        }

    }

}
