//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 12:36:44 PM CET 
//


package io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for relationInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="relationInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="relationType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="isPartOf"/>
 *               &lt;enumeration value="isPartWith"/>
 *               &lt;enumeration value="hasPart"/>
 *               &lt;enumeration value="hasOutcome"/>
 *               &lt;enumeration value="isCombinedWith"/>
 *               &lt;enumeration value="requiresLR"/>
 *               &lt;enumeration value="requiresSoftware"/>
 *               &lt;enumeration value="isExactMatch"/>
 *               &lt;enumeration value="isSimilarTo"/>
 *               &lt;enumeration value="isContinuationOf"/>
 *               &lt;enumeration value="isVersionOf"/>
 *               &lt;enumeration value="isSimilarTo"/>
 *               &lt;enumeration value="replaces"/>
 *               &lt;enumeration value="isReplacedWith"/>
 *               &lt;enumeration value="isCreatedBy"/>
 *               &lt;enumeration value="isElicitedBy"/>
 *               &lt;enumeration value="isRecordedBy"/>
 *               &lt;enumeration value="isEditedBy"/>
 *               &lt;enumeration value="isAnalysedBy"/>
 *               &lt;enumeration value="isEvaluatedBy"/>
 *               &lt;enumeration value="isQueriedBy"/>
 *               &lt;enumeration value="isAccessedBy"/>
 *               &lt;enumeration value="isArchivedBy"/>
 *               &lt;enumeration value="isDisplayedBy"/>
 *               &lt;enumeration value="isCompatibleWith"/>
 *               &lt;enumeration value="isAnnotatedVersionOf"/>
 *               &lt;enumeration value="hasAnnotatedVersion"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="relatedResource" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}relatedResourceType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "relationInfoType", propOrder = {
    "relationType",
    "relatedResource"
})
public class RelationInfoType {

    @XmlElement(required = true)
    protected String relationType;
    @XmlElement(required = true)
    protected RelatedResourceType relatedResource;

    /**
     * Gets the value of the relationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationType() {
        return relationType;
    }

    /**
     * Sets the value of the relationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationType(String value) {
        this.relationType = value;
    }

    /**
     * Gets the value of the relatedResource property.
     * 
     * @return
     *     possible object is
     *     {@link RelatedResourceType }
     *     
     */
    public RelatedResourceType getRelatedResource() {
        return relatedResource;
    }

    /**
     * Sets the value of the relatedResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelatedResourceType }
     *     
     */
    public void setRelatedResource(RelatedResourceType value) {
        this.relatedResource = value;
    }

}
