//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 12:36:44 PM CET 
//


package io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Base type for repositories
 * 
 * <p>Java class for repositoryInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="repositoryInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="repositoryNames">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="repositoryName" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;restriction base="&lt;http://www.meta-share.org/OMTD-SHARE_XMLSchema>myString">
 *                         &lt;/restriction>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="repositoryIdentifiers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="repositoryIdentifier" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}repositoryIdentifierType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "repositoryInfoType", propOrder = {
    "repositoryNames",
    "repositoryIdentifiers"
})
public class RepositoryInfoType {

    @XmlElement(required = true)
    protected RepositoryInfoType.RepositoryNames repositoryNames;
    @XmlElement(required = true)
    protected RepositoryInfoType.RepositoryIdentifiers repositoryIdentifiers;

    /**
     * Gets the value of the repositoryNames property.
     * 
     * @return
     *     possible object is
     *     {@link RepositoryInfoType.RepositoryNames }
     *     
     */
    public RepositoryInfoType.RepositoryNames getRepositoryNames() {
        return repositoryNames;
    }

    /**
     * Sets the value of the repositoryNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepositoryInfoType.RepositoryNames }
     *     
     */
    public void setRepositoryNames(RepositoryInfoType.RepositoryNames value) {
        this.repositoryNames = value;
    }

    /**
     * Gets the value of the repositoryIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link RepositoryInfoType.RepositoryIdentifiers }
     *     
     */
    public RepositoryInfoType.RepositoryIdentifiers getRepositoryIdentifiers() {
        return repositoryIdentifiers;
    }

    /**
     * Sets the value of the repositoryIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepositoryInfoType.RepositoryIdentifiers }
     *     
     */
    public void setRepositoryIdentifiers(RepositoryInfoType.RepositoryIdentifiers value) {
        this.repositoryIdentifiers = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="repositoryIdentifier" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}repositoryIdentifierType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "repositoryIdentifier"
    })
    public static class RepositoryIdentifiers {

        @XmlElement(required = true)
        protected List<RepositoryIdentifierType> repositoryIdentifier;

        /**
         * Gets the value of the repositoryIdentifier property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the repositoryIdentifier property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRepositoryIdentifier().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RepositoryIdentifierType }
         * 
         * 
         */
        public List<RepositoryIdentifierType> getRepositoryIdentifier() {
            if (repositoryIdentifier == null) {
                repositoryIdentifier = new ArrayList<RepositoryIdentifierType>();
            }
            return this.repositoryIdentifier;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="repositoryName" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;restriction base="&lt;http://www.meta-share.org/OMTD-SHARE_XMLSchema>myString">
     *               &lt;/restriction>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "repositoryName"
    })
    public static class RepositoryNames {

        @XmlElement(required = true)
        protected List<RepositoryInfoType.RepositoryNames.RepositoryName> repositoryName;

        /**
         * Gets the value of the repositoryName property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the repositoryName property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRepositoryName().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RepositoryInfoType.RepositoryNames.RepositoryName }
         * 
         * 
         */
        public List<RepositoryInfoType.RepositoryNames.RepositoryName> getRepositoryName() {
            if (repositoryName == null) {
                repositoryName = new ArrayList<RepositoryInfoType.RepositoryNames.RepositoryName>();
            }
            return this.repositoryName;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;restriction base="&lt;http://www.meta-share.org/OMTD-SHARE_XMLSchema>myString">
         *     &lt;/restriction>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class RepositoryName
            extends MyString
        {


        }

    }

}
