//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 12:36:44 PM CET 
//


package io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Base type for identifier schemes for resources (corpora, lexical/conceptual resources etc.)
 * 
 * <p>Java class for resourceIdentifierType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resourceIdentifierType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="resourceIdentifierSchemeName" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="DOI"/>
 *             &lt;enumeration value="ISLRN"/>
 *             &lt;enumeration value="Handle"/>
 *             &lt;enumeration value="ARK"/>
 *             &lt;enumeration value="arXiv"/>
 *             &lt;enumeration value="bibcode"/>
 *             &lt;enumeration value="EAN13"/>
 *             &lt;enumeration value="EISSN"/>
 *             &lt;enumeration value="ISBN"/>
 *             &lt;enumeration value="ISSN"/>
 *             &lt;enumeration value="ISTC"/>
 *             &lt;enumeration value="LISSN"/>
 *             &lt;enumeration value="LSID"/>
 *             &lt;enumeration value="PURL"/>
 *             &lt;enumeration value="UPC"/>
 *             &lt;enumeration value="URL"/>
 *             &lt;enumeration value="URN"/>
 *             &lt;enumeration value="OAI"/>
 *             &lt;enumeration value="PMCID"/>
 *             &lt;enumeration value="PMID"/>
 *             &lt;enumeration value="maven"/>
 *             &lt;enumeration value="docker"/>
 *             &lt;enumeration value="OMTD-docker"/>
 *             &lt;enumeration value="OMTD"/>
 *             &lt;enumeration value="other"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}schemeURI"/>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resourceIdentifierType", propOrder = {
    "value"
})
public class ResourceIdentifierType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "resourceIdentifierSchemeName", required = true)
    protected String resourceIdentifierSchemeName;
    @XmlAttribute(name = "schemeURI", namespace = "http://www.meta-share.org/OMTD-SHARE_XMLSchema")
    @XmlSchemaType(name = "anyURI")
    protected String schemeURI;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the resourceIdentifierSchemeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceIdentifierSchemeName() {
        return resourceIdentifierSchemeName;
    }

    /**
     * Sets the value of the resourceIdentifierSchemeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceIdentifierSchemeName(String value) {
        this.resourceIdentifierSchemeName = value;
    }

    /**
     * Gets the value of the schemeURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemeURI() {
        return schemeURI;
    }

    /**
     * Sets the value of the schemeURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemeURI(String value) {
        this.schemeURI = value;
    }

}
