//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 12:36:44 PM CET 
//


package io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="licenceInfos">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}licenceInfo" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}rightsStatement"/>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}attributionText" minOccurs="0"/>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}copyrightStatement" minOccurs="0"/>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}availabilityStartDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}availabilityEndDate" minOccurs="0"/>
 *         &lt;element name="rightsHolders" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}rightsHolder" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "licenceInfos",
    "rightsStatement",
    "attributionText",
    "copyrightStatement",
    "availabilityStartDate",
    "availabilityEndDate",
    "rightsHolders"
})
@XmlRootElement(name = "rightsInfo")
public class RightsInfo {

    @XmlElement(required = true)
    protected RightsInfo.LicenceInfos licenceInfos;
    @XmlElement(required = true)
    protected String rightsStatement;
    protected String attributionText;
    protected String copyrightStatement;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar availabilityStartDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar availabilityEndDate;
    protected RightsInfo.RightsHolders rightsHolders;

    /**
     * Gets the value of the licenceInfos property.
     * 
     * @return
     *     possible object is
     *     {@link RightsInfo.LicenceInfos }
     *     
     */
    public RightsInfo.LicenceInfos getLicenceInfos() {
        return licenceInfos;
    }

    /**
     * Sets the value of the licenceInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link RightsInfo.LicenceInfos }
     *     
     */
    public void setLicenceInfos(RightsInfo.LicenceInfos value) {
        this.licenceInfos = value;
    }

    /**
     * Gets the value of the rightsStatement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRightsStatement() {
        return rightsStatement;
    }

    /**
     * Sets the value of the rightsStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRightsStatement(String value) {
        this.rightsStatement = value;
    }

    /**
     * The text that must be quoted for attribution purposes when using a resource - for cases where a resource is provided with a restriction on attribution; you can use a standard text such as "Resource A by Resource Creator/Owner B used under licence C as accessed at D"
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttributionText() {
        return attributionText;
    }

    /**
     * Sets the value of the attributionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributionText(String value) {
        this.attributionText = value;
    }

    /**
     * A free text statement that may be included with the resource, usually containing the name(s) of copyright holders and licensing terms (intended for resources that already have such a statement).
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyrightStatement() {
        return copyrightStatement;
    }

    /**
     * Sets the value of the copyrightStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyrightStatement(String value) {
        this.copyrightStatement = value;
    }

    /**
     * Specifies the start date of availability of a resource - only for cases where a resource is available for a restricted time period.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAvailabilityStartDate() {
        return availabilityStartDate;
    }

    /**
     * Sets the value of the availabilityStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAvailabilityStartDate(XMLGregorianCalendar value) {
        this.availabilityStartDate = value;
    }

    /**
     * Specifies the end date of availability of a resource - only for cases where a resource is available for a restricted time period.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAvailabilityEndDate() {
        return availabilityEndDate;
    }

    /**
     * Sets the value of the availabilityEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAvailabilityEndDate(XMLGregorianCalendar value) {
        this.availabilityEndDate = value;
    }

    /**
     * Gets the value of the rightsHolders property.
     * 
     * @return
     *     possible object is
     *     {@link RightsInfo.RightsHolders }
     *     
     */
    public RightsInfo.RightsHolders getRightsHolders() {
        return rightsHolders;
    }

    /**
     * Sets the value of the rightsHolders property.
     * 
     * @param value
     *     allowed object is
     *     {@link RightsInfo.RightsHolders }
     *     
     */
    public void setRightsHolders(RightsInfo.RightsHolders value) {
        this.rightsHolders = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}licenceInfo" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "licenceInfo"
    })
    public static class LicenceInfos {

        @XmlElement(required = true)
        protected List<LicenceInfoType> licenceInfo;

        /**
         * Groups information on licences for the resource; can be repeated to allow for different modes of access and restrictions of use (e.g. free for academic use, on-a-fee basis for commercial use, download of a sample for free use etc.) Gets the value of the licenceInfo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the licenceInfo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLicenceInfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LicenceInfoType }
         * 
         * 
         */
        public List<LicenceInfoType> getLicenceInfo() {
            if (licenceInfo == null) {
                licenceInfo = new ArrayList<LicenceInfoType>();
            }
            return this.licenceInfo;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}rightsHolder" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rightsHolder"
    })
    public static class RightsHolders {

        protected List<ActorInfoType> rightsHolder;

        /**
         * Groups information on a person or an organization who holds the Copyright and SGDB rights that subsist in the resource. The rights holder could be different from the creator that may have assigned the rights to another person or organization (e.g. an author as a creator assigns her rights to the publisher who is the rights holder) and the distributor that holds a specific licence (i.e. a permission) to distribute the work.Gets the value of the rightsHolder property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the rightsHolder property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRightsHolder().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ActorInfoType }
         * 
         * 
         */
        public List<ActorInfoType> getRightsHolder() {
            if (rightsHolder == null) {
                rightsHolder = new ArrayList<ActorInfoType>();
            }
            return this.rightsHolder;
        }

    }

}
