//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 12:36:44 PM CET 
//


package io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for scriptIdType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="scriptIdType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Afak"/>
 *     &lt;enumeration value="Aghb"/>
 *     &lt;enumeration value="Ahom"/>
 *     &lt;enumeration value="Arab"/>
 *     &lt;enumeration value="Armi"/>
 *     &lt;enumeration value="Armn"/>
 *     &lt;enumeration value="Avst"/>
 *     &lt;enumeration value="Bali"/>
 *     &lt;enumeration value="Bamu"/>
 *     &lt;enumeration value="Bass"/>
 *     &lt;enumeration value="Batk"/>
 *     &lt;enumeration value="Beng"/>
 *     &lt;enumeration value="Blis"/>
 *     &lt;enumeration value="Bopo"/>
 *     &lt;enumeration value="Brah"/>
 *     &lt;enumeration value="Brai"/>
 *     &lt;enumeration value="Bugi"/>
 *     &lt;enumeration value="Buhd"/>
 *     &lt;enumeration value="Cakm"/>
 *     &lt;enumeration value="Cans"/>
 *     &lt;enumeration value="Cari"/>
 *     &lt;enumeration value="Cham"/>
 *     &lt;enumeration value="Cher"/>
 *     &lt;enumeration value="Cirt"/>
 *     &lt;enumeration value="Copt"/>
 *     &lt;enumeration value="Cprt"/>
 *     &lt;enumeration value="Cyrl"/>
 *     &lt;enumeration value="Cyrs"/>
 *     &lt;enumeration value="Deva"/>
 *     &lt;enumeration value="Dsrt"/>
 *     &lt;enumeration value="Dupl"/>
 *     &lt;enumeration value="Egyd"/>
 *     &lt;enumeration value="Egyh"/>
 *     &lt;enumeration value="Egyp"/>
 *     &lt;enumeration value="Elba"/>
 *     &lt;enumeration value="Ethi"/>
 *     &lt;enumeration value="Geok"/>
 *     &lt;enumeration value="Geor"/>
 *     &lt;enumeration value="Glag"/>
 *     &lt;enumeration value="Goth"/>
 *     &lt;enumeration value="Gran"/>
 *     &lt;enumeration value="Grek"/>
 *     &lt;enumeration value="Gujr"/>
 *     &lt;enumeration value="Guru"/>
 *     &lt;enumeration value="Hang"/>
 *     &lt;enumeration value="Hani"/>
 *     &lt;enumeration value="Hano"/>
 *     &lt;enumeration value="Hans"/>
 *     &lt;enumeration value="Hant"/>
 *     &lt;enumeration value="Hatr"/>
 *     &lt;enumeration value="Hebr"/>
 *     &lt;enumeration value="Hira"/>
 *     &lt;enumeration value="Hluw"/>
 *     &lt;enumeration value="Hmng"/>
 *     &lt;enumeration value="Hrkt"/>
 *     &lt;enumeration value="Hung"/>
 *     &lt;enumeration value="Inds"/>
 *     &lt;enumeration value="Ital"/>
 *     &lt;enumeration value="Java"/>
 *     &lt;enumeration value="Jpan"/>
 *     &lt;enumeration value="Jurc"/>
 *     &lt;enumeration value="Kali"/>
 *     &lt;enumeration value="Kana"/>
 *     &lt;enumeration value="Khar"/>
 *     &lt;enumeration value="Khmr"/>
 *     &lt;enumeration value="Khoj"/>
 *     &lt;enumeration value="Knda"/>
 *     &lt;enumeration value="Kore"/>
 *     &lt;enumeration value="Kpel"/>
 *     &lt;enumeration value="Kthi"/>
 *     &lt;enumeration value="Lana"/>
 *     &lt;enumeration value="Laoo"/>
 *     &lt;enumeration value="Latf"/>
 *     &lt;enumeration value="Latg"/>
 *     &lt;enumeration value="Latn"/>
 *     &lt;enumeration value="Lepc"/>
 *     &lt;enumeration value="Limb"/>
 *     &lt;enumeration value="Lina"/>
 *     &lt;enumeration value="Linb"/>
 *     &lt;enumeration value="Lisu"/>
 *     &lt;enumeration value="Loma"/>
 *     &lt;enumeration value="Lyci"/>
 *     &lt;enumeration value="Lydi"/>
 *     &lt;enumeration value="Mahj"/>
 *     &lt;enumeration value="Mand"/>
 *     &lt;enumeration value="Mani"/>
 *     &lt;enumeration value="Maya"/>
 *     &lt;enumeration value="Mend"/>
 *     &lt;enumeration value="Merc"/>
 *     &lt;enumeration value="Mero"/>
 *     &lt;enumeration value="Mlym"/>
 *     &lt;enumeration value="Modi"/>
 *     &lt;enumeration value="Mong"/>
 *     &lt;enumeration value="Moon"/>
 *     &lt;enumeration value="Mroo"/>
 *     &lt;enumeration value="Mtei"/>
 *     &lt;enumeration value="Mult"/>
 *     &lt;enumeration value="Mymr"/>
 *     &lt;enumeration value="Narb"/>
 *     &lt;enumeration value="Nbat"/>
 *     &lt;enumeration value="Nkgb"/>
 *     &lt;enumeration value="Nkoo"/>
 *     &lt;enumeration value="Nshu"/>
 *     &lt;enumeration value="Ogam"/>
 *     &lt;enumeration value="Olck"/>
 *     &lt;enumeration value="Orkh"/>
 *     &lt;enumeration value="Orya"/>
 *     &lt;enumeration value="Osma"/>
 *     &lt;enumeration value="Palm"/>
 *     &lt;enumeration value="Pauc"/>
 *     &lt;enumeration value="Perm"/>
 *     &lt;enumeration value="Phag"/>
 *     &lt;enumeration value="Phli"/>
 *     &lt;enumeration value="Phlp"/>
 *     &lt;enumeration value="Phlv"/>
 *     &lt;enumeration value="Phnx"/>
 *     &lt;enumeration value="Plrd"/>
 *     &lt;enumeration value="Prti"/>
 *     &lt;enumeration value="Qaaa..Qabx"/>
 *     &lt;enumeration value="Rjng"/>
 *     &lt;enumeration value="Roro"/>
 *     &lt;enumeration value="Runr"/>
 *     &lt;enumeration value="Samr"/>
 *     &lt;enumeration value="Sara"/>
 *     &lt;enumeration value="Sarb"/>
 *     &lt;enumeration value="Saur"/>
 *     &lt;enumeration value="Sgnw"/>
 *     &lt;enumeration value="Shaw"/>
 *     &lt;enumeration value="Shrd"/>
 *     &lt;enumeration value="Sidd"/>
 *     &lt;enumeration value="Sind"/>
 *     &lt;enumeration value="Sinh"/>
 *     &lt;enumeration value="Sora"/>
 *     &lt;enumeration value="Sund"/>
 *     &lt;enumeration value="Sylo"/>
 *     &lt;enumeration value="Syrc"/>
 *     &lt;enumeration value="Syre"/>
 *     &lt;enumeration value="Syrj"/>
 *     &lt;enumeration value="Syrn"/>
 *     &lt;enumeration value="Tagb"/>
 *     &lt;enumeration value="Takr"/>
 *     &lt;enumeration value="Tale"/>
 *     &lt;enumeration value="Talu"/>
 *     &lt;enumeration value="Taml"/>
 *     &lt;enumeration value="Tang"/>
 *     &lt;enumeration value="Tavt"/>
 *     &lt;enumeration value="Telu"/>
 *     &lt;enumeration value="Teng"/>
 *     &lt;enumeration value="Tfng"/>
 *     &lt;enumeration value="Tglg"/>
 *     &lt;enumeration value="Thaa"/>
 *     &lt;enumeration value="Thai"/>
 *     &lt;enumeration value="Tibt"/>
 *     &lt;enumeration value="Tirh"/>
 *     &lt;enumeration value="Ugar"/>
 *     &lt;enumeration value="Vaii"/>
 *     &lt;enumeration value="Visp"/>
 *     &lt;enumeration value="Wara"/>
 *     &lt;enumeration value="Wole"/>
 *     &lt;enumeration value="Xpeo"/>
 *     &lt;enumeration value="Xsux"/>
 *     &lt;enumeration value="Yiii"/>
 *     &lt;enumeration value="Zinh"/>
 *     &lt;enumeration value="Zmth"/>
 *     &lt;enumeration value="Zsym"/>
 *     &lt;enumeration value="Zxxx"/>
 *     &lt;enumeration value="Zyyy"/>
 *     &lt;enumeration value="Zzzz"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "scriptIdType")
@XmlEnum
public enum ScriptIdType {

    @XmlEnumValue("Afak")
    AFAK("Afak"),
    @XmlEnumValue("Aghb")
    AGHB("Aghb"),
    @XmlEnumValue("Ahom")
    AHOM("Ahom"),
    @XmlEnumValue("Arab")
    ARAB("Arab"),
    @XmlEnumValue("Armi")
    ARMI("Armi"),
    @XmlEnumValue("Armn")
    ARMN("Armn"),
    @XmlEnumValue("Avst")
    AVST("Avst"),
    @XmlEnumValue("Bali")
    BALI("Bali"),
    @XmlEnumValue("Bamu")
    BAMU("Bamu"),
    @XmlEnumValue("Bass")
    BASS("Bass"),
    @XmlEnumValue("Batk")
    BATK("Batk"),
    @XmlEnumValue("Beng")
    BENG("Beng"),
    @XmlEnumValue("Blis")
    BLIS("Blis"),
    @XmlEnumValue("Bopo")
    BOPO("Bopo"),
    @XmlEnumValue("Brah")
    BRAH("Brah"),
    @XmlEnumValue("Brai")
    BRAI("Brai"),
    @XmlEnumValue("Bugi")
    BUGI("Bugi"),
    @XmlEnumValue("Buhd")
    BUHD("Buhd"),
    @XmlEnumValue("Cakm")
    CAKM("Cakm"),
    @XmlEnumValue("Cans")
    CANS("Cans"),
    @XmlEnumValue("Cari")
    CARI("Cari"),
    @XmlEnumValue("Cham")
    CHAM("Cham"),
    @XmlEnumValue("Cher")
    CHER("Cher"),
    @XmlEnumValue("Cirt")
    CIRT("Cirt"),
    @XmlEnumValue("Copt")
    COPT("Copt"),
    @XmlEnumValue("Cprt")
    CPRT("Cprt"),
    @XmlEnumValue("Cyrl")
    CYRL("Cyrl"),
    @XmlEnumValue("Cyrs")
    CYRS("Cyrs"),
    @XmlEnumValue("Deva")
    DEVA("Deva"),
    @XmlEnumValue("Dsrt")
    DSRT("Dsrt"),
    @XmlEnumValue("Dupl")
    DUPL("Dupl"),
    @XmlEnumValue("Egyd")
    EGYD("Egyd"),
    @XmlEnumValue("Egyh")
    EGYH("Egyh"),
    @XmlEnumValue("Egyp")
    EGYP("Egyp"),
    @XmlEnumValue("Elba")
    ELBA("Elba"),
    @XmlEnumValue("Ethi")
    ETHI("Ethi"),
    @XmlEnumValue("Geok")
    GEOK("Geok"),
    @XmlEnumValue("Geor")
    GEOR("Geor"),
    @XmlEnumValue("Glag")
    GLAG("Glag"),
    @XmlEnumValue("Goth")
    GOTH("Goth"),
    @XmlEnumValue("Gran")
    GRAN("Gran"),
    @XmlEnumValue("Grek")
    GREK("Grek"),
    @XmlEnumValue("Gujr")
    GUJR("Gujr"),
    @XmlEnumValue("Guru")
    GURU("Guru"),
    @XmlEnumValue("Hang")
    HANG("Hang"),
    @XmlEnumValue("Hani")
    HANI("Hani"),
    @XmlEnumValue("Hano")
    HANO("Hano"),
    @XmlEnumValue("Hans")
    HANS("Hans"),
    @XmlEnumValue("Hant")
    HANT("Hant"),
    @XmlEnumValue("Hatr")
    HATR("Hatr"),
    @XmlEnumValue("Hebr")
    HEBR("Hebr"),
    @XmlEnumValue("Hira")
    HIRA("Hira"),
    @XmlEnumValue("Hluw")
    HLUW("Hluw"),
    @XmlEnumValue("Hmng")
    HMNG("Hmng"),
    @XmlEnumValue("Hrkt")
    HRKT("Hrkt"),
    @XmlEnumValue("Hung")
    HUNG("Hung"),
    @XmlEnumValue("Inds")
    INDS("Inds"),
    @XmlEnumValue("Ital")
    ITAL("Ital"),
    @XmlEnumValue("Java")
    JAVA("Java"),
    @XmlEnumValue("Jpan")
    JPAN("Jpan"),
    @XmlEnumValue("Jurc")
    JURC("Jurc"),
    @XmlEnumValue("Kali")
    KALI("Kali"),
    @XmlEnumValue("Kana")
    KANA("Kana"),
    @XmlEnumValue("Khar")
    KHAR("Khar"),
    @XmlEnumValue("Khmr")
    KHMR("Khmr"),
    @XmlEnumValue("Khoj")
    KHOJ("Khoj"),
    @XmlEnumValue("Knda")
    KNDA("Knda"),
    @XmlEnumValue("Kore")
    KORE("Kore"),
    @XmlEnumValue("Kpel")
    KPEL("Kpel"),
    @XmlEnumValue("Kthi")
    KTHI("Kthi"),
    @XmlEnumValue("Lana")
    LANA("Lana"),
    @XmlEnumValue("Laoo")
    LAOO("Laoo"),
    @XmlEnumValue("Latf")
    LATF("Latf"),
    @XmlEnumValue("Latg")
    LATG("Latg"),
    @XmlEnumValue("Latn")
    LATN("Latn"),
    @XmlEnumValue("Lepc")
    LEPC("Lepc"),
    @XmlEnumValue("Limb")
    LIMB("Limb"),
    @XmlEnumValue("Lina")
    LINA("Lina"),
    @XmlEnumValue("Linb")
    LINB("Linb"),
    @XmlEnumValue("Lisu")
    LISU("Lisu"),
    @XmlEnumValue("Loma")
    LOMA("Loma"),
    @XmlEnumValue("Lyci")
    LYCI("Lyci"),
    @XmlEnumValue("Lydi")
    LYDI("Lydi"),
    @XmlEnumValue("Mahj")
    MAHJ("Mahj"),
    @XmlEnumValue("Mand")
    MAND("Mand"),
    @XmlEnumValue("Mani")
    MANI("Mani"),
    @XmlEnumValue("Maya")
    MAYA("Maya"),
    @XmlEnumValue("Mend")
    MEND("Mend"),
    @XmlEnumValue("Merc")
    MERC("Merc"),
    @XmlEnumValue("Mero")
    MERO("Mero"),
    @XmlEnumValue("Mlym")
    MLYM("Mlym"),
    @XmlEnumValue("Modi")
    MODI("Modi"),
    @XmlEnumValue("Mong")
    MONG("Mong"),
    @XmlEnumValue("Moon")
    MOON("Moon"),
    @XmlEnumValue("Mroo")
    MROO("Mroo"),
    @XmlEnumValue("Mtei")
    MTEI("Mtei"),
    @XmlEnumValue("Mult")
    MULT("Mult"),
    @XmlEnumValue("Mymr")
    MYMR("Mymr"),
    @XmlEnumValue("Narb")
    NARB("Narb"),
    @XmlEnumValue("Nbat")
    NBAT("Nbat"),
    @XmlEnumValue("Nkgb")
    NKGB("Nkgb"),
    @XmlEnumValue("Nkoo")
    NKOO("Nkoo"),
    @XmlEnumValue("Nshu")
    NSHU("Nshu"),
    @XmlEnumValue("Ogam")
    OGAM("Ogam"),
    @XmlEnumValue("Olck")
    OLCK("Olck"),
    @XmlEnumValue("Orkh")
    ORKH("Orkh"),
    @XmlEnumValue("Orya")
    ORYA("Orya"),
    @XmlEnumValue("Osma")
    OSMA("Osma"),
    @XmlEnumValue("Palm")
    PALM("Palm"),
    @XmlEnumValue("Pauc")
    PAUC("Pauc"),
    @XmlEnumValue("Perm")
    PERM("Perm"),
    @XmlEnumValue("Phag")
    PHAG("Phag"),
    @XmlEnumValue("Phli")
    PHLI("Phli"),
    @XmlEnumValue("Phlp")
    PHLP("Phlp"),
    @XmlEnumValue("Phlv")
    PHLV("Phlv"),
    @XmlEnumValue("Phnx")
    PHNX("Phnx"),
    @XmlEnumValue("Plrd")
    PLRD("Plrd"),
    @XmlEnumValue("Prti")
    PRTI("Prti"),
    @XmlEnumValue("Qaaa..Qabx")
    QAAA_QABX("Qaaa..Qabx"),
    @XmlEnumValue("Rjng")
    RJNG("Rjng"),
    @XmlEnumValue("Roro")
    RORO("Roro"),
    @XmlEnumValue("Runr")
    RUNR("Runr"),
    @XmlEnumValue("Samr")
    SAMR("Samr"),
    @XmlEnumValue("Sara")
    SARA("Sara"),
    @XmlEnumValue("Sarb")
    SARB("Sarb"),
    @XmlEnumValue("Saur")
    SAUR("Saur"),
    @XmlEnumValue("Sgnw")
    SGNW("Sgnw"),
    @XmlEnumValue("Shaw")
    SHAW("Shaw"),
    @XmlEnumValue("Shrd")
    SHRD("Shrd"),
    @XmlEnumValue("Sidd")
    SIDD("Sidd"),
    @XmlEnumValue("Sind")
    SIND("Sind"),
    @XmlEnumValue("Sinh")
    SINH("Sinh"),
    @XmlEnumValue("Sora")
    SORA("Sora"),
    @XmlEnumValue("Sund")
    SUND("Sund"),
    @XmlEnumValue("Sylo")
    SYLO("Sylo"),
    @XmlEnumValue("Syrc")
    SYRC("Syrc"),
    @XmlEnumValue("Syre")
    SYRE("Syre"),
    @XmlEnumValue("Syrj")
    SYRJ("Syrj"),
    @XmlEnumValue("Syrn")
    SYRN("Syrn"),
    @XmlEnumValue("Tagb")
    TAGB("Tagb"),
    @XmlEnumValue("Takr")
    TAKR("Takr"),
    @XmlEnumValue("Tale")
    TALE("Tale"),
    @XmlEnumValue("Talu")
    TALU("Talu"),
    @XmlEnumValue("Taml")
    TAML("Taml"),
    @XmlEnumValue("Tang")
    TANG("Tang"),
    @XmlEnumValue("Tavt")
    TAVT("Tavt"),
    @XmlEnumValue("Telu")
    TELU("Telu"),
    @XmlEnumValue("Teng")
    TENG("Teng"),
    @XmlEnumValue("Tfng")
    TFNG("Tfng"),
    @XmlEnumValue("Tglg")
    TGLG("Tglg"),
    @XmlEnumValue("Thaa")
    THAA("Thaa"),
    @XmlEnumValue("Thai")
    THAI("Thai"),
    @XmlEnumValue("Tibt")
    TIBT("Tibt"),
    @XmlEnumValue("Tirh")
    TIRH("Tirh"),
    @XmlEnumValue("Ugar")
    UGAR("Ugar"),
    @XmlEnumValue("Vaii")
    VAII("Vaii"),
    @XmlEnumValue("Visp")
    VISP("Visp"),
    @XmlEnumValue("Wara")
    WARA("Wara"),
    @XmlEnumValue("Wole")
    WOLE("Wole"),
    @XmlEnumValue("Xpeo")
    XPEO("Xpeo"),
    @XmlEnumValue("Xsux")
    XSUX("Xsux"),
    @XmlEnumValue("Yiii")
    YIII("Yiii"),
    @XmlEnumValue("Zinh")
    ZINH("Zinh"),
    @XmlEnumValue("Zmth")
    ZMTH("Zmth"),
    @XmlEnumValue("Zsym")
    ZSYM("Zsym"),
    @XmlEnumValue("Zxxx")
    ZXXX("Zxxx"),
    @XmlEnumValue("Zyyy")
    ZYYY("Zyyy"),
    @XmlEnumValue("Zzzz")
    ZZZZ("Zzzz");
    private final String value;

    ScriptIdType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ScriptIdType fromValue(String v) {
        for (ScriptIdType c: ScriptIdType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
