//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 12:36:44 PM CET 
//


package io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for structuralEncodingInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="structuralEncodingInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="structuralEncoding">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="schemeName" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="jats"/>
 *                       &lt;enumeration value="teiP5"/>
 *                       &lt;enumeration value="other"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="schemeURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sizePerStructuralEncoding" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}sizeInfoType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "structuralEncodingInfoType", propOrder = {
    "structuralEncoding",
    "sizePerStructuralEncoding"
})
public class StructuralEncodingInfoType {

    @XmlElement(required = true)
    protected StructuralEncodingInfoType.StructuralEncoding structuralEncoding;
    protected SizeInfoType sizePerStructuralEncoding;

    /**
     * Gets the value of the structuralEncoding property.
     * 
     * @return
     *     possible object is
     *     {@link StructuralEncodingInfoType.StructuralEncoding }
     *     
     */
    public StructuralEncodingInfoType.StructuralEncoding getStructuralEncoding() {
        return structuralEncoding;
    }

    /**
     * Sets the value of the structuralEncoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link StructuralEncodingInfoType.StructuralEncoding }
     *     
     */
    public void setStructuralEncoding(StructuralEncodingInfoType.StructuralEncoding value) {
        this.structuralEncoding = value;
    }

    /**
     * Gets the value of the sizePerStructuralEncoding property.
     * 
     * @return
     *     possible object is
     *     {@link SizeInfoType }
     *     
     */
    public SizeInfoType getSizePerStructuralEncoding() {
        return sizePerStructuralEncoding;
    }

    /**
     * Sets the value of the sizePerStructuralEncoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link SizeInfoType }
     *     
     */
    public void setSizePerStructuralEncoding(SizeInfoType value) {
        this.sizePerStructuralEncoding = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="schemeName" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="jats"/>
     *             &lt;enumeration value="teiP5"/>
     *             &lt;enumeration value="other"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="schemeURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class StructuralEncoding {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "schemeName", required = true)
        protected String schemeName;
        @XmlAttribute(name = "schemeURI")
        @XmlSchemaType(name = "anyURI")
        protected String schemeURI;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the schemeName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSchemeName() {
            return schemeName;
        }

        /**
         * Sets the value of the schemeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSchemeName(String value) {
            this.schemeName = value;
        }

        /**
         * Gets the value of the schemeURI property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSchemeURI() {
            return schemeURI;
        }

        /**
         * Sets the value of the schemeURI property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSchemeURI(String value) {
            this.schemeURI = value;
        }

    }

}
