//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 12:36:44 PM CET 
//


package io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for timeCoverageInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="timeCoverageInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="timeCoverage">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="sizePerTimeCoverage" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}sizeInfoType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "timeCoverageInfoType", propOrder = {
    "timeCoverage",
    "sizePerTimeCoverage"
})
public class TimeCoverageInfoType {

    @XmlElement(required = true)
    protected String timeCoverage;
    protected SizeInfoType sizePerTimeCoverage;

    /**
     * Gets the value of the timeCoverage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeCoverage() {
        return timeCoverage;
    }

    /**
     * Sets the value of the timeCoverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeCoverage(String value) {
        this.timeCoverage = value;
    }

    /**
     * Gets the value of the sizePerTimeCoverage property.
     * 
     * @return
     *     possible object is
     *     {@link SizeInfoType }
     *     
     */
    public SizeInfoType getSizePerTimeCoverage() {
        return sizePerTimeCoverage;
    }

    /**
     * Sets the value of the sizePerTimeCoverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link SizeInfoType }
     *     
     */
    public void setSizePerTimeCoverage(SizeInfoType value) {
        this.sizePerTimeCoverage = value;
    }

}
