//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.01 at 12:36:44 PM CET 
//


package io.github.agroportal.ncboproxy.servlet.handlers.omtdsharemeta.xsdmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for validationInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="validationInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="validated" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="validationType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *               &lt;enumeration value="formal"/>
 *               &lt;enumeration value="content"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="validationMode" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}processMode" minOccurs="0"/>
 *         &lt;element name="validationModeDetails" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="500"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="validationExtent" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *               &lt;enumeration value="full"/>
 *               &lt;enumeration value="partial"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="validationExtentDetails" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="500"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="validationReports" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="hasValidationReport" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}relatedDocumentInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="validationSwComponents" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="isValidatedBy" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}relatedResourceType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="validators" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="validator" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}actorInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "validationInfoType", propOrder = {
    "validated",
    "validationType",
    "validationMode",
    "validationModeDetails",
    "validationExtent",
    "validationExtentDetails",
    "validationReports",
    "validationSwComponents",
    "validators"
})
public class ValidationInfoType {

    protected boolean validated;
    protected String validationType;
    @XmlSchemaType(name = "string")
    protected ProcessMode validationMode;
    protected String validationModeDetails;
    protected String validationExtent;
    protected String validationExtentDetails;
    protected ValidationInfoType.ValidationReports validationReports;
    protected ValidationInfoType.ValidationSwComponents validationSwComponents;
    protected ValidationInfoType.Validators validators;

    /**
     * Gets the value of the validated property.
     * 
     */
    public boolean isValidated() {
        return validated;
    }

    /**
     * Sets the value of the validated property.
     * 
     */
    public void setValidated(boolean value) {
        this.validated = value;
    }

    /**
     * Gets the value of the validationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidationType() {
        return validationType;
    }

    /**
     * Sets the value of the validationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidationType(String value) {
        this.validationType = value;
    }

    /**
     * Gets the value of the validationMode property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessMode }
     *     
     */
    public ProcessMode getValidationMode() {
        return validationMode;
    }

    /**
     * Sets the value of the validationMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessMode }
     *     
     */
    public void setValidationMode(ProcessMode value) {
        this.validationMode = value;
    }

    /**
     * Gets the value of the validationModeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidationModeDetails() {
        return validationModeDetails;
    }

    /**
     * Sets the value of the validationModeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidationModeDetails(String value) {
        this.validationModeDetails = value;
    }

    /**
     * Gets the value of the validationExtent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidationExtent() {
        return validationExtent;
    }

    /**
     * Sets the value of the validationExtent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidationExtent(String value) {
        this.validationExtent = value;
    }

    /**
     * Gets the value of the validationExtentDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidationExtentDetails() {
        return validationExtentDetails;
    }

    /**
     * Sets the value of the validationExtentDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidationExtentDetails(String value) {
        this.validationExtentDetails = value;
    }

    /**
     * Gets the value of the validationReports property.
     * 
     * @return
     *     possible object is
     *     {@link ValidationInfoType.ValidationReports }
     *     
     */
    public ValidationInfoType.ValidationReports getValidationReports() {
        return validationReports;
    }

    /**
     * Sets the value of the validationReports property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidationInfoType.ValidationReports }
     *     
     */
    public void setValidationReports(ValidationInfoType.ValidationReports value) {
        this.validationReports = value;
    }

    /**
     * Gets the value of the validationSwComponents property.
     * 
     * @return
     *     possible object is
     *     {@link ValidationInfoType.ValidationSwComponents }
     *     
     */
    public ValidationInfoType.ValidationSwComponents getValidationSwComponents() {
        return validationSwComponents;
    }

    /**
     * Sets the value of the validationSwComponents property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidationInfoType.ValidationSwComponents }
     *     
     */
    public void setValidationSwComponents(ValidationInfoType.ValidationSwComponents value) {
        this.validationSwComponents = value;
    }

    /**
     * Gets the value of the validators property.
     * 
     * @return
     *     possible object is
     *     {@link ValidationInfoType.Validators }
     *     
     */
    public ValidationInfoType.Validators getValidators() {
        return validators;
    }

    /**
     * Sets the value of the validators property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidationInfoType.Validators }
     *     
     */
    public void setValidators(ValidationInfoType.Validators value) {
        this.validators = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="hasValidationReport" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}relatedDocumentInfoType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hasValidationReport"
    })
    public static class ValidationReports {

        protected List<RelatedDocumentInfoType> hasValidationReport;

        /**
         * Gets the value of the hasValidationReport property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the hasValidationReport property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHasValidationReport().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RelatedDocumentInfoType }
         * 
         * 
         */
        public List<RelatedDocumentInfoType> getHasValidationReport() {
            if (hasValidationReport == null) {
                hasValidationReport = new ArrayList<RelatedDocumentInfoType>();
            }
            return this.hasValidationReport;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="isValidatedBy" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}relatedResourceType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "isValidatedBy"
    })
    public static class ValidationSwComponents {

        protected List<RelatedResourceType> isValidatedBy;

        /**
         * Gets the value of the isValidatedBy property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the isValidatedBy property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIsValidatedBy().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RelatedResourceType }
         * 
         * 
         */
        public List<RelatedResourceType> getIsValidatedBy() {
            if (isValidatedBy == null) {
                isValidatedBy = new ArrayList<RelatedResourceType>();
            }
            return this.isValidatedBy;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="validator" type="{http://www.meta-share.org/OMTD-SHARE_XMLSchema}actorInfoType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "validator"
    })
    public static class Validators {

        protected List<ActorInfoType> validator;

        /**
         * Gets the value of the validator property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the validator property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValidator().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ActorInfoType }
         * 
         * 
         */
        public List<ActorInfoType> getValidator() {
            if (validator == null) {
                validator = new ArrayList<ActorInfoType>();
            }
            return this.validator;
        }

    }

}
